/* Canonical section titles verified against the official source texts. */
(function(){
  globalThis.__CHAPTER_TITLES=Object.freeze({
  "uop-art-1": "Przepisy ogólne",
  "uop-art-4": "Organizacja Policji",
  "uop-art-14": "Zakres uprawnień Policji",
  "uop-art-22a": "Bandera i znaki rozpoznawcze",
  "uop-art-25": "Służba w Policji",
  "kw-art-1": "Zasady odpowiedzialności",
  "kw-art-18": "Kary, środki karne i zasady ich wymiaru",
  "kw-art-40": "Zastosowanie środków oddziaływania wychowawczego",
  "kw-art-42": "Warunkowe zawieszenie wykonania kary aresztu",
  "kw-art-45": "Przedawnienie orzekania, wykonania kary oraz zatarcie ukarania",
  "kw-art-47": "Wyjaśnienie wyrażeń ustawowych",
  "kw-art-48": "Stosunek do ustaw szczególnych",
  "kw-art-49": "Wykroczenia przeciwko porządkowi i spokojowi publicznemu",
  "kw-art-65": "Wykroczenia przeciwko instytucjom państwowym, samorządowym i społecznym",
  "kw-art-70": "Wykroczenia przeciwko bezpieczeństwu osób i mienia",
  "kw-art-84": "Wykroczenia przeciwko bezpieczeństwu i porządkowi w komunikacji",
  "kw-art-104": "Wykroczenia przeciwko osobie",
  "kw-art-109": "Wykroczenia przeciwko zdrowiu",
  "kw-art-119": "Wykroczenia przeciwko mieniu",
  "kw-art-132": "Wykroczenia przeciwko interesom konsumentów",
  "kw-art-140": "Wykroczenia przeciwko obyczajności publicznej",
  "kw-art-143": "Wykroczenia przeciwko urządzeniom użytku publicznego",
  "kw-art-146": "Wykroczenia przeciwko obowiązkowi ewidencji",
  "kw-art-148": "Szkodnictwo leśne, polne i ogrodowe",
  "kk-art-1": "Zasady odpowiedzialności karnej",
  "kk-art-13": "Formy popełnienia przestępstwa",
  "kk-art-25": "Wyłączenie odpowiedzialności karnej",
  "kk-art-32": "Kary",
  "kk-art-39": "Środki karne",
  "kk-art-44": "Przepadek i środki kompensacyjne",
  "kk-art-53": "Zasady wymiaru kary i środków karnych",
  "kk-art-64": "Powrót do przestępstwa",
  "kk-art-66": "Środki związane z poddaniem sprawcy próbie",
  "kk-art-85": "Zbieg przestępstw oraz łączenie kar i środków karnych",
  "kk-art-93": "Środki zabezpieczające",
  "kk-art-101": "Przedawnienie",
  "kk-art-106": "Zatarcie skazania",
  "kk-art-109": "Odpowiedzialność za przestępstwa popełnione za granicą",
  "kk-art-115": "Objaśnienie wyrażeń ustawowych",
  "kk-art-116": "Stosunek do ustaw szczególnych",
  "kk-art-117": "Przestępstwa przeciwko pokojowi, ludzkości oraz przestępstwa wojenne",
  "kk-art-127": "Przestępstwa przeciwko Rzeczypospolitej Polskiej",
  "kk-art-140": "Przestępstwa przeciwko obronności",
  "kk-art-148": "Przestępstwa przeciwko życiu i zdrowiu",
  "kk-art-163": "Przestępstwa przeciwko bezpieczeństwu powszechnemu",
  "kk-art-173": "Przestępstwa przeciwko bezpieczeństwu w komunikacji",
  "kk-art-181": "Przestępstwa przeciwko środowisku",
  "kk-art-189": "Przestępstwa przeciwko wolności",
  "kk-art-194": "Przestępstwa przeciwko wolności sumienia i wyznania",
  "kk-art-197": "Przestępstwa przeciwko wolności seksualnej i obyczajności",
  "kk-art-206": "Przestępstwa przeciwko rodzinie i opiece",
  "kk-art-212": "Przestępstwa przeciwko czci i nietykalności cielesnej",
  "kk-art-218": "Przestępstwa przeciwko prawom osób wykonujących pracę zarobkową",
  "kk-art-222": "Przestępstwa przeciwko działalności instytucji państwowych oraz samorządu terytorialnego",
  "kk-art-232": "Przestępstwa przeciwko wymiarowi sprawiedliwości",
  "kk-art-248": "Przestępstwa przeciwko wyborom i referendum",
  "kk-art-252": "Przestępstwa przeciwko porządkowi publicznemu",
  "kk-art-265": "Przestępstwa przeciwko ochronie informacji",
  "kk-art-270": "Przestępstwa przeciwko wiarygodności dokumentów",
  "kk-art-278": "Przestępstwa przeciwko mieniu",
  "kk-art-296": "Przestępstwa przeciwko obrotowi gospodarczemu i interesom majątkowym w obrocie cywilnoprawnym",
  "kk-art-310": "Przestępstwa przeciwko obrotowi pieniędzmi i papierami wartościowymi",
  "kk-art-317": "Przepisy ogólne dotyczące żołnierzy",
  "kk-art-338": "Przestępstwa przeciwko obowiązkowi pełnienia służby wojskowej",
  "kk-art-343": "Przestępstwa przeciwko zasadom dyscypliny wojskowej",
  "kk-art-350": "Przestępstwa przeciwko zasadom postępowania z podwładnymi",
  "kk-art-354": "Przestępstwa przeciwko zasadom obchodzenia się z uzbrojeniem i uzbrojonym sprzętem wojskowym",
  "kk-art-356": "Przestępstwa przeciwko zasadom pełnienia służby",
  "kk-art-358": "Przestępstwa przeciwko mieniu wojskowemu",
  "kpk-art-1": "Przepisy wstępne",
  "kpk-art-24": "Właściwość i skład sądu",
  "kpk-art-40": "Wyłączenie sędziego",
  "kpk-art-45": "Oskarżyciel publiczny",
  "kpk-art-49": "Pokrzywdzony",
  "kpk-art-53": "Oskarżyciel posiłkowy",
  "kpk-art-59": "Oskarżyciel prywatny",
  "kpk-art-71": "Oskarżony",
  "kpk-art-82": "Obrońcy i pełnomocnicy",
  "kpk-art-90": "Przedstawiciel społeczny",
  "kpk-art-91a": "Podmiot zobowiązany",
  "kpk-art-91b": "Właściciel przedsiębiorstwa zagrożonego przepadkiem",
  "kpk-art-92": "Orzeczenia, zarządzenia i polecenia",
  "kpk-art-108": "Narada i głosowanie",
  "kpk-art-116": "Porządek czynności procesowych",
  "kpk-art-122": "Terminy",
  "kpk-art-128": "Doręczenia",
  "kpk-art-143": "Protokoły",
  "kpk-art-156": "Przeglądanie akt i sporządzanie odpisów",
  "kpk-art-160": "Odtworzenie zaginionych lub zniszczonych akt",
  "kpk-art-167": "Przepisy ogólne",
  "kpk-art-175": "Wyjaśnienia oskarżonego",
  "kpk-art-177": "Świadkowie",
  "kpk-art-193": "Biegli, tłumacze, specjaliści",
  "kpk-art-207": "Oględziny. Otwarcie zwłok. Eksperyment procesowy",
  "kpk-art-213": "Wywiad środowiskowy i badanie osoby oskarżonego",
  "kpk-art-217": "Zatrzymanie rzeczy. Przeszukanie",
  "kpk-art-237": "Kontrola i utrwalanie rozmów",
  "kpk-art-243": "Zatrzymanie",
  "kpk-art-249": "Środki zapobiegawcze",
  "kpk-art-278": "Poszukiwanie oskarżonego i list gończy",
  "kpk-art-281": "List żelazny",
  "kpk-art-285": "Kary porządkowe",
  "kpk-art-291": "Zabezpieczenie majątkowe",
  "kpk-art-297": "Przepisy ogólne",
  "kpk-art-303": "Wszczęcie śledztwa",
  "kpk-art-309": "Przebieg śledztwa",
  "kpk-art-321": "Zamknięcie śledztwa",
  "kpk-art-325a": "Dochodzenie",
  "kpk-art-326": "Nadzór prokuratora nad postępowaniem przygotowawczym",
  "kpk-art-329": "Czynności sądowe w postępowaniu przygotowawczym",
  "kpk-art-331": "Akt oskarżenia",
  "kpk-art-337": "Wstępna kontrola oskarżenia",
  "kpk-art-348": "Przygotowanie do rozprawy głównej",
  "kpk-art-355": "Jawność rozprawy głównej",
  "kpk-art-365": "Przepisy ogólne o rozprawie głównej",
  "kpk-art-381": "Rozpoczęcie rozprawy głównej",
  "kpk-art-385": "Przewód sądowy",
  "kpk-art-406": "Głosy końcowe",
  "kpk-art-408": "Wyrokowanie",
  "kpk-art-425": "Przepisy ogólne",
  "kpk-art-444": "Apelacja",
  "kpk-art-459": "Zażalenie i sprzeciw",
  "kpk-art-485": "Postępowanie w sprawach z oskarżenia prywatnego",
  "kpk-art-500": "Postępowanie nakazowe",
  "kpk-art-517a": "Postępowanie przyspieszone",
  "kpk-art-518": "Kasacja",
  "kpk-art-539a": "Skarga na wyrok sądu odwoławczego",
  "kpk-art-540": "Wznowienie postępowania",
  "kpk-art-549": "Podjęcie postępowania warunkowo umorzonego",
  "kpk-art-552": "Odszkodowanie za niesłuszne skazanie, tymczasowe aresztowanie lub zatrzymanie",
  "kpk-art-560": "Ułaskawienie",
  "kpk-art-568a": "Orzekanie kary łącznej",
  "kpk-art-577a": "Współpraca z Prokuraturą Europejską",
  "kpk-art-578": "Immunitety osób należących do przedstawicielstw dyplomatycznych i urzędów konsularnych państw obcych",
  "kpk-art-585": "Pomoc prawna i doręczenia w sprawach karnych",
  "kpk-art-589g": "Wystąpienie do państwa członkowskiego Unii Europejskiej o wykonanie postanowienia o zatrzymaniu dowodów lub mającego na celu zabezpieczenie mienia",
  "kpk-art-589l": "Wystąpienie państwa członkowskiego Unii Europejskiej o wykonanie orzeczenia o zatrzymaniu dowodów lub mającego na celu zabezpieczenie mienia",
  "kpk-art-589w": "Wystąpienie do państwa członkowskiego Unii Europejskiej o przeprowadzenie czynności dochodzeniowych na podstawie europejskiego nakazu dochodzeniowego",
  "kpk-art-589ze": "Wystąpienie państwa członkowskiego Unii Europejskiej o przeprowadzenie czynności dochodzeniowych na podstawie europejskiego nakazu dochodzeniowego",
  "kpk-art-590": "Przejęcie i przekazanie ścigania karnego",
  "kpk-art-593": "Wystąpienie o wydanie lub przewóz osób ściganych lub skazanych przebywających za granicą oraz o wydanie przedmiotów",
  "kpk-art-602": "Wydanie oraz przewóz osób ściganych albo skazanych lub wydanie przedmiotów na wniosek państw obcych",
  "kpk-art-607a": "Wystąpienie do państwa członkowskiego Unii Europejskiej o przekazanie osoby ściganej na podstawie europejskiego nakazu aresztowania",
  "kpk-art-607k": "Wystąpienie państwa członkowskiego Unii Europejskiej o przekazanie osoby ściganej na podstawie europejskiego nakazu aresztowania",
  "kpk-art-607zd": "Wystąpienie do państwa członkowskiego Unii Europejskiej o wykonanie środka zapobiegawczego",
  "kpk-art-607zh": "Wystąpienie państwa członkowskiego Unii Europejskiej o wykonanie orzeczenia wydanego w celu zapewnienia prawidłowego toku postępowania",
  "kpk-art-608": "Przejęcie i przekazanie orzeczeń do wykonania",
  "kpk-art-611fa": "Wystąpienie do państwa członkowskiego Unii Europejskiej o wykonanie orzeczenia dotyczącego grzywny, nawiązki, świadczenia pieniężnego lub orzeczenia zasądzającego od sprawcy koszty procesu",
  "kpk-art-611ff": "Wystąpienie państwa członkowskiego Unii Europejskiej o wykonanie orzeczenia o karach o charakterze pieniężnym",
  "kpk-art-611fn": "Wystąpienie do państwa członkowskiego Unii Europejskiej o wykonanie orzeczenia przepadku",
  "kpk-art-611fu": "Wystąpienie państwa członkowskiego Unii Europejskiej o wykonanie orzeczenia przepadku",
  "kpk-art-611g": "Współpraca z Międzynarodowym Trybunałem Karnym",
  "kpk-art-611t": "Wystąpienie do państwa członkowskiego Unii Europejskiej o wykonanie kary pozbawienia wolności",
  "kpk-art-611tg": "Wystąpienie państwa członkowskiego Unii Europejskiej o wykonanie kary pozbawienia wolności",
  "kpk-art-611u": "Wystąpienie do państwa członkowskiego Unii Europejskiej o wykonanie orzeczenia skazującego na karę pozbawienia wolności z warunkowym zawieszeniem jej wykonania, karę ograniczenia wolności, samoistnie orzeczony środek karny, a także orzeczenia o warunkowym zwolnieniu oraz warunkowym umorzeniu postępowania karnego",
  "kpk-art-611ud": "Wystąpienie państwa członkowskiego Unii Europejskiej o wykonanie orzeczenia karnego związanego z poddaniem sprawcy próbie",
  "kpk-art-611w": "Wystąpienie do państwa członkowskiego Unii Europejskiej o wykonanie europejskiego nakazu ochrony",
  "kpk-art-611wd": "Wystąpienie państwa członkowskiego Unii Europejskiej o wykonanie europejskiego nakazu ochrony",
  "kpk-art-612": "Przepisy końcowe",
  "kpk-art-616": "Przepisy ogólne",
  "kpk-art-623": "Zwolnienie od kosztów sądowych",
  "kpk-art-626": "Zasądzenie kosztów procesu",
  "kpk-art-646": "Przepisy ogólne",
  "kpk-art-663": "Środki przymusu i postępowanie przygotowawcze",
  "kpk-art-669": "Postępowanie przed sądem",
  "kpow-art-1": "Zasady ogólne",
  "kpow-art-9": "Właściwość i skład sądu",
  "kpow-art-16": "Wyłączenie sędziego",
  "kpow-art-17": "Oskarżyciel publiczny",
  "kpow-art-20": "Obwiniony i jego obrońca",
  "kpow-art-25": "Pokrzywdzony, oskarżyciel posiłkowy i pełnomocnicy",
  "kpow-art-32": "Czynności procesowe",
  "kpow-art-39": "Przepisy ogólne",
  "kpow-art-41": "Przeprowadzanie poszczególnych dowodów. Przeszukanie",
  "kpow-art-45": "Zatrzymanie",
  "kpow-art-48": "Zabezpieczenie i zajęcie przedmiotów",
  "kpow-art-49": "Kary porządkowe i pozostałe środki przymusu",
  "kpow-art-54": "Czynności wyjaśniające",
  "kpow-art-57": "Wszczęcie postępowania. Orzekanie przed rozprawą",
  "kpow-art-65": "Przygotowanie do rozprawy",
  "kpow-art-70": "Rozprawa",
  "kpow-art-85": "Postępowanie w sprawach osób podlegających orzecznictwu sądów wojskowych",
  "kpow-art-89": "Postępowanie przyspieszone",
  "kpow-art-93": "Postępowanie nakazowe",
  "kpow-art-95": "Postępowanie mandatowe",
  "kpow-art-103": "Środki odwoławcze",
  "kpow-art-110": "Kasacja",
  "kpow-art-113": "Wznowienie postępowania",
  "kpow-art-114": "Odszkodowanie za niesłuszne ukaranie lub zatrzymanie",
  "kpow-art-116a": "Wystąpienie do państwa członkowskiego Unii Europejskiej o wykonanie postanowienia o zatrzymaniu dowodów lub mającego na celu zabezpieczenie mienia oraz wykonanie orzeczenia sądu lub innego organu państwa członkowskiego Unii Europejskiej o zatrzymaniu dowodów lub mającego na celu zabezpieczenie mienia",
  "kpow-art-116b": "Wystąpienie do państwa członkowskiego Unii Europejskiej o wykonanie grzywny, środków karnych w postaci nawiązki lub obowiązku naprawienia szkody lub też orzeczenia zasądzającego koszty postępowania oraz wykonanie orzeczenia sądu lub innego organu państwa członkowskiego Unii Europejskiej o karach o charakterze pieniężnym",
  "kpow-art-116c": "Wystąpienie do państwa członkowskiego Unii Europejskiej o przeprowadzenie dowodu na podstawie europejskiego nakazu dochodzeniowego oraz wykonanie europejskiego nakazu dochodzeniowego wydanego w innym państwie członkowskim Unii Europejskiej",
  "kpow-art-117": "Koszty postępowania",
  "spb-art-1": "Przepisy ogólne",
  "spb-art-11": "Środki przymusu bezpośredniego",
  "spb-art-45": "Broń palna",
  "spb-art-51": "Dokumentowanie użycia i wykorzystania środków przymusu bezpośredniego i broni palnej",
  "spb-art-81": "Przepisy przejściowe i przepis końcowy",
  "prd-art-1": "Przepisy ogólne",
  "prd-art-3": "Zasady ogólne",
  "prd-art-11": "Ruch pieszych oraz osób poruszających się przy użyciu urządzenia wspomagającego ruch",
  "prd-art-16": "Zasady ogólne",
  "prd-art-17": "Włączanie się do ruchu",
  "prd-art-19": "Prędkość i hamowanie",
  "prd-art-22": "Zmiana kierunku jazdy lub pasa ruchu",
  "prd-art-23": "Wymijanie, omijanie i cofanie",
  "prd-art-24": "Wyprzedzanie",
  "prd-art-25": "Przecinanie się kierunków ruchu",
  "prd-art-29": "Ostrzeganie oraz jazda w warunkach zmniejszonej przejrzystości powietrza",
  "prd-art-31": "Holowanie",
  "prd-art-32": "Ruch pojazdów w kolumnie",
  "prd-art-33": "Przepisy dodatkowe o ruchu rowerów, hulajnóg elektrycznych, urządzeń transportu osobistego, motorowerów oraz pojazdów zaprzęgowych",
  "prd-art-35": "Ruch zwierząt",
  "prd-art-38": "Przepisy porządkowe",
  "prd-art-46": "Zatrzymanie i postój",
  "prd-art-51": "Używanie świateł zewnętrznych",
  "prd-art-53": "Warunki używania pojazdów w ruchu drogowym",
  "prd-art-65": "Wykorzystanie dróg w sposób szczególny",
  "prd-art-65k": "Wykorzystanie dróg na potrzeby prac badawczych nad pojazdami autonomicznymi",
  "prd-art-65o": "Dopuszczenie do ruchu samochodów osobowych przeznaczonych do zawodów sportowych",
  "prd-art-66": "Warunki techniczne pojazdów",
  "prd-art-66a": {
    "prefix": "Rozdział I",
    "title": "Warunki techniczne pojazdów"
  },
  "prd-art-71": "Warunki dopuszczenia pojazdów do ruchu",
  "prd-art-80a": "Centralna ewidencja pojazdów",
  "prd-art-80k": "Krajowy Punkt Kontaktowy",
  "prd-art-80s": "Profesjonalna rejestracja pojazdów",
  "prd-art-81": "Badania techniczne pojazdów",
  "prd-art-100a": "Centralna ewidencja kierowców",
  "prd-art-100f": "Centralna ewidencja posiadaczy kart parkingowych",
  "prd-art-114": "(uchylony)",
  "prd-art-116": "Wojewódzki ośrodek ruchu drogowego",
  "prd-art-129": "Uprawnienia Policji i innych organów",
  "prd-art-132": "Zatrzymywanie i zwracanie dowodów rejestracyjnych",
  "prd-art-135": "Zatrzymywanie praw jazdy i pozwoleń oraz cofanie i przywracanie uprawnień do kierowania pojazdami",
  "prd-art-140aa": "Kary pieniężne za przejazd pojazdów nienormatywnych bez zezwolenia lub niezgodnie z warunkami określonymi w zezwoleniu",
  "prd-art-140b": "Działania na rzecz bezpieczeństwa ruchu drogowego",
  "prd-art-140m": "Kary pieniężne",
  "prd-art-140o": "Przetwarzanie danych osobowych",
  "prd-art-144": "Zmiany w przepisach obowiązujących, przepisy epizodyczne, przejściowe i końcowe",
  "cudz-art-1": "Przepisy ogólne",
  "cudz-art-16": "Szef Urzędu do Spraw Cudzoziemców",
  "cudz-art-23": "Zasady przekraczania granicy",
  "cudz-art-37": "Przekraczanie granicy w ramach małego ruchu granicznego",
  "cudz-art-49": "Zaproszenia",
  "cudz-art-58": "Wydawanie wiz",
  "cudz-art-82": "Przedłużanie wiz",
  "cudz-art-90": "Cofanie i unieważnianie wiz",
  "cudz-art-98": "Część ogólna",
  "cudz-art-114": "Zezwolenie na pobyt czasowy i pracę",
  "cudz-art-127": "Zezwolenie na pobyt czasowy w celu wykonywania pracy w zawodzie wymagającym wysokich kwalifikacji. Mobilność długoterminowa posiadacza Niebieskiej Karty UE",
  "cudz-art-139a": "Zezwolenie na pobyt czasowy w celu wykonywania pracy w ramach przeniesienia wewnątrz przedsiębiorstwa. Mobilność krótkoterminowa i długoterminowa pracownika kadry kierowniczej, specjalisty lub pracownika odbywającego staż, w ramach przeniesienia wewnątrz przedsiębiorstwa",
  "cudz-art-140": "Zezwolenie na pobyt czasowy w celu wykonywania pracy przez cudzoziemca delegowanego przez pracodawcę zagranicznego na terytorium Rzeczypospolitej Polskiej",
  "cudz-art-142": "Zezwolenie na pobyt czasowy w celu prowadzenia działalności gospodarczej",
  "cudz-art-144": "Zezwolenie na pobyt czasowy w celu kształcenia się na studiach. Mobilność studenta",
  "cudz-art-151": "Zezwolenie na pobyt czasowy w celu prowadzenia badań naukowych. Mobilność krótkoterminowa i długoterminowa naukowca",
  "cudz-art-157a": "Zezwolenie na pobyt czasowy dla stażysty",
  "cudz-art-157g": "Zezwolenie na pobyt czasowy dla wolontariusza",
  "cudz-art-158": "Zezwolenie na pobyt czasowy dla członków rodzin obywateli Rzeczypospolitej Polskiej oraz członków rodzin cudzoziemców. Mobilność krótkoterminowa i długoterminowa członków rodzin naukowców",
  "cudz-art-170": "Pobyt na terytorium Rzeczypospolitej Polskiej cudzoziemców będących ofiarami handlu ludźmi",
  "cudz-art-181": "Zezwolenie na pobyt czasowy ze względu na okoliczności wymagające krótkotrwałego pobytu",
  "cudz-art-185a": "Zezwolenie na pobyt czasowy ze względu na pracę sezonową",
  "cudz-art-186": "Zezwolenie na pobyt czasowy ze względu na inne okoliczności",
  "cudz-art-195": "Zezwolenie na pobyt stały",
  "cudz-art-211": "Zezwolenie na pobyt rezydenta długoterminowego UE",
  "cudz-art-226": "Dokumenty wydawane cudzoziemcom",
  "cudz-art-288": "Kontrola legalności pobytu cudzoziemców na terytorium Rzeczypospolitej Polskiej",
  "cudz-art-299": "Zobowiązanie cudzoziemca do powrotu",
  "cudz-art-347a": "Umieszczanie, aktualizacja i usuwanie w Systemie Informacyjnym Schengen do celów, o których mowa w art. 3 ust. 1 rozporządzenia nr 2018/1860, danych cudzoziemców, którym zostały wydane decyzje o zobowiązaniu cudzoziemca do powrotu, oraz konsultacje w tych sprawach",
  "cudz-art-348": "Zgoda na pobyt ze względów humanitarnych oraz zgoda na pobyt tolerowany",
  "cudz-art-360": "Tranzyt cudzoziemca drogą powietrzną",
  "cudz-art-380": "Wykonanie decyzji o zobowiązaniu cudzoziemca do powrotu wydanej przez organ innego państwa członkowskiego Unii Europejskiej",
  "cudz-art-393a": "Przekazanie do innego państwa członkowskiego na podstawie rozporządzenia 604/2013 cudzoziemca, który nie ubiega się o udzielenie ochrony międzynarodowej",
  "cudz-art-393c": "Postępowanie dotyczące cudzoziemca, którego dane zostały umieszczone w Systemie Informacyjnym Schengen do celów, o których mowa w art. 3 ust. 1 rozporządzenia nr 2018/1860, w razie wyjazdu z terytorium państw obszaru Schengen oraz w trakcie pobytu na terytorium Rzeczypospolitej Polskiej",
  "cudz-art-394": "Postępowanie w sprawie zatrzymania cudzoziemca, umieszczenie go w strzeżonym ośrodku lub zastosowanie wobec niego aresztu dla cudzoziemców",
  "cudz-art-410": "Pobyt cudzoziemców w strzeżonym ośrodku lub w areszcie dla cudzoziemców",
  "cudz-art-428": "Rejestry w sprawach cudzoziemców i ewidencja zaproszeń",
  "cudz-art-434": "Wykaz cudzoziemców, których pobyt na terytorium Rzeczypospolitej Polskiej jest niepożądany",
  "cudz-art-449": "Krajowy zbiór rejestrów, ewidencji i wykazu w sprawach cudzoziemców",
  "cudz-art-459": "Odpowiedzialność przewoźnika",
  "cudz-art-464": "Przepisy karne",
  "cudz-art-507": "Przepisy przejściowe i końcowe",
  "nieletni-art-1": "Przepisy ogólne",
  "nieletni-art-6": "Środki przeciwdziałania demoralizacji nieletnich i dopuszczaniu się przez nich czynów karalnych",
  "nieletni-art-23": "Przepisy ogólne",
  "nieletni-art-35": "Strony i pokrzywdzony",
  "nieletni-art-42": "Środki tymczasowe i zatrzymanie",
  "nieletni-art-52": "Postępowanie w pierwszej instancji",
  "nieletni-art-78": "Postępowanie odwoławcze",
  "nieletni-art-87": "Przepisy ogólne",
  "nieletni-art-107": "Prawa i obowiązki nieletnich",
  "nieletni-art-143": "Nadzór nad wykonywaniem orzeczeń",
  "nieletni-art-144": "Przepisy ogólne",
  "nieletni-art-147": "Upomnienie",
  "nieletni-art-148": "Zobowiązanie nieletniego do określonego postępowania",
  "nieletni-art-154": "Nadzór odpowiedzialny rodziców albo opiekuna nieletniego",
  "nieletni-art-155": "Czynności kuratora sądowego oraz nadzór organizacji społecznej, pracodawcy albo osoby godnej zaufania",
  "nieletni-art-162": "Ośrodki kuratorskie",
  "nieletni-art-174": "Skierowanie do organizacji lub instytucji",
  "nieletni-art-176": "Umieszczenie w rodzinie zastępczej zawodowej",
  "nieletni-art-177": "Umieszczenie w młodzieżowym ośrodku wychowawczym",
  "nieletni-art-186": "Umieszczenie w okręgowym ośrodku wychowawczym",
  "nieletni-art-212": "Wykonywanie środka leczniczego",
  "nieletni-art-233": "Wykonywanie środka poprawczego",
  "nieletni-art-286": "Wykonywanie zobowiązania rodziców albo opiekuna nieletniego",
  "nieletni-art-289": "Wykonywanie środków tymczasowych",
  "nieletni-art-321": "Organizacja okręgowych ośrodków wychowawczych, zakładów poprawczych i schronisk dla nieletnich",
  "nieletni-art-345": "Zapewnienie bezpieczeństwa w okręgowych ośrodkach wychowawczych, zakładach poprawczych i schroniskach dla nieletnich",
  "nieletni-art-358": "Ochrona danych osobowych",
  "nieletni-art-393": "Przepisy przejściowe i dostosowujące",
  "nieletni-art-416": "Przepisy końcowe",
  "z768-par-1": {
    "prefix": "Rozdział I",
    "title": "Przepisy ogólne"
  },
  "z768-par-8": "Organizacja służby",
  "z768-par-24": "Pełnienie służby patrolowej",
  "z768-par-39": "Nadzór nad pełnieniem służby patrolowej",
  "z768-par-44": "Przepisy końcowe",
  "z360-par-1": {
    "prefix": "Rozdział I",
    "title": "Przepisy ogólne"
  },
  "z805-par-1": "Zasady etyki zawodowej policjanta"
});
})();
