/* Favorites: article filter, fragment editor, article-edge swipe and long-press actions. */
(function(){
  const KEY='police-law-bookmarks-v1',FILTER_KEY='police-law-favorites-filter-v1',HIGHLIGHT_KEY='police-law-favorites-highlight-v1';
  const view=document.getElementById('actview'),M=globalThis.__FAVORITES_MODEL;if(!view||!M)return;
  let filter=false,highlight=true,allActs=false,activeArticle=null,touch=null,pointer=null,editor=null,activeQueued=false,lastReadingArticle='',swipeCloseTimer=0,allSignature='',singleActCode='',allActiveId='',allViewCycle=0,drawerResizeObserver=null;
  const expanded=new Set(),collapsedActs=new Set(),lawTitleMeasure=document.createElement('canvas').getContext('2d');
  try{localStorage.setItem(FILTER_KEY,'0');localStorage.setItem(HIGHLIGHT_KEY,'1')}catch(_){}
  const read=()=>{try{const value=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(value)?value:[]}catch(_){return[]}};
  const actForCode=code=>{try{return DATA?.find(act=>act[0]===code)||null}catch(_){return null}};
  let dataIndex=null,indexedLength=-1;
  function ensureDataIndex(){const acts=Array.isArray(DATA)?DATA:[],length=acts.reduce((sum,act)=>sum+(act[3]?.length||0),0);if(dataIndex&&indexedLength===length)return dataIndex;const rows=new Map(),actById=new Map();for(const act of acts)for(const row of act[3]||[]){rows.set(row[0],row);actById.set(row[0],act)}indexedLength=length;return dataIndex={rows,actById}}
  const actForId=id=>ensureDataIndex().actById.get(id)||null;
  const rowFor=id=>ensureDataIndex().rows.get(id)||null;
  const metaFor=act=>{try{return (typeof META!=='undefined'&&META[act[0]])||[act[0],act[1],'']}catch(_){return[act[0],act[1],'']}};
  const itemFor=id=>read().find(item=>item.id===id)||null;
  function save(items){try{localStorage.setItem(KEY,JSON.stringify(items))}catch(_){}window.dispatchEvent(new CustomEvent('police-law-favorites-change'))}
  function persistModes(){try{localStorage.setItem(FILTER_KEY,filter?'1':'0');localStorage.setItem(HIGHLIGHT_KEY,highlight?'1':'0')}catch(_){}}
  function syncLegacy(){try{if(typeof populateDrawer==='function')populateDrawer();if(typeof updateUI==='function')updateUI()}catch(_){}}
  const icon=name=>({
    star:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m12 3 2.75 5.57 6.15.9-4.45 4.33 1.05 6.12L12 17.03l-5.5 2.89 1.05-6.12L3.1 9.47l6.15-.9L12 3Z"/></svg>',
    eye:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M2.5 12s3.45-5.5 9.5-5.5 9.5 5.5 9.5 5.5-3.45 5.5-9.5 5.5S2.5 12 2.5 12Z"/><circle cx="12" cy="12" r="2.8"/></svg>',
    edit:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m4 20 4.2-1 10.9-10.9a2.1 2.1 0 0 0-3-3L5.2 16 4 20Z"/><path d="m14.7 6.5 3 3"/></svg>',
    trash:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 7h14M9 7V4h6v3m-8 0 1 13h8l1-13M10 10v7m4-7v7"/></svg>'
  }[name]||'');
  function removeFavorite(id){closeArticlePopover();closeSwipe(true);save(read().filter(item=>item.id!==id));syncLegacy()}
  function addFavorite(id){const items=read(),row=rowFor(id),act=actForId(id);if(!row||!act||items.some(item=>item.id===id))return;closeArticlePopover();closeSwipe(true);items.unshift({id,act:act[0],num:row[2],topic:row[3]||''});save(items);syncLegacy()}
  function closeScopePopover(){document.querySelector('.favorites-scope-popover')?.remove()}
  function closeArticlePopover(){document.querySelector('.favorite-article-popover')?.remove()}
  function setAllActs(next,code,targetId=null){
    closeScopePopover();closeArticlePopover();
    if(next){
      const items=read();if(!items.length)return;
      singleActCode=code||ACT?.[0]||singleActCode;
      const current=[...view.querySelectorAll('article.legal-unit')].find(article=>{const rect=article.getBoundingClientRect(),top=(document.querySelector('.top')?.getBoundingClientRect().bottom||0)+8;return rect.top<=top&&rect.bottom>top});
      allActiveId=current&&items.some(item=>item.id===current.id)?current.id:'';
      allActs=true;filter=true;expanded.clear();collapsedActs.clear();allViewCycle++;persistModes();allSignature='';refresh();return;
    }
    allActs=false;filter=false;highlight=true;allSignature='';allActiveId='';expanded.clear();collapsedActs.clear();persistModes();
    const target=code||singleActCode||ACT?.[0];
    document.body.classList.remove('favorites-all-acts');view.classList.remove('favorites-all-view');
    const list=document.getElementById('drawerArticles');if(list){list.classList.remove('favorites-all-drawer');delete list.dataset.favoritesAllSignature}
    document.querySelectorAll('.quickbar button').forEach(button=>button.classList.remove('favorites-all-visible'));
    if(target&&typeof renderAct==='function')renderAct(target,targetId,false);
    globalThis.__POLICE_DRAWER_REFRESH?.();
    setTimeout(refresh,40);
  }
  globalThis.__FAVORITES_OPEN_SINGLE=(code,id)=>setAllActs(false,code,id);
  function disableFavoritesSearch(){if(allActs){setAllActs(false);return}if(!filter)return;filter=false;expanded.clear();persistModes();refresh()}
  globalThis.__POLICE_FAVORITES_SEARCH={isActive:()=>filter||allActs,ids:()=>read().map(item=>item.id).filter(Boolean),disable:disableFavoritesSearch};
  function showScopePopover(anchor){
    closeScopePopover();closeArticlePopover();
    const pop=document.createElement('div');pop.className='favorites-scope-popover';pop.setAttribute('role','menu');
    const toggle=document.createElement('button');toggle.type='button';toggle.className='favorites-scope-toggle';toggle.setAttribute('role','menuitemcheckbox');toggle.setAttribute('aria-checked',String(allActs));toggle.innerHTML='<span class="favorites-scope-info">Wszystkie ustawy</span><span class="favorites-scope-switch" aria-hidden="true"></span>';toggle.onclick=()=>setAllActs(!allActs);
    pop.appendChild(toggle);document.body.appendChild(pop);
    requestAnimationFrame(()=>{const anchorRect=anchor.getBoundingClientRect(),center=anchorRect.left+anchorRect.width/2,margin=6,width=pop.offsetWidth,left=Math.max(margin,Math.min(window.innerWidth-margin-width,center-width/2));pop.style.left=left+'px';pop.style.top=anchorRect.bottom+8+'px';pop.style.setProperty('--scope-caret-x',Math.max(15,Math.min(width-15,center-left))+'px');pop.classList.add('show')});
  }
  function installScopeGesture(button){
    if(button.dataset.scopeGesture)return;button.dataset.scopeGesture='1';
    let timer=0,long=false;const clear=()=>{clearTimeout(timer);timer=0};
    button.addEventListener('pointerdown',event=>{if(event.pointerType==='mouse'&&event.button!==0)return;long=false;clear();timer=setTimeout(()=>{long=true;button.dataset.longPress='1';showScopePopover(button);navigator.vibrate?.(12)},360)});
    button.addEventListener('pointermove',event=>{if(!timer)return;const rect=button.getBoundingClientRect();if(event.clientX<rect.left-28||event.clientX>rect.right+28||event.clientY<rect.top-28||event.clientY>rect.bottom+68)clear()});
    button.addEventListener('pointerup',event=>{clear();if(long){const target=document.elementFromPoint(event.clientX,event.clientY)?.closest('.favorites-scope-toggle');if(target)target.click();setTimeout(()=>delete button.dataset.longPress,0)}});
    button.addEventListener('pointercancel',clear);button.addEventListener('contextmenu',event=>{event.preventDefault();showScopePopover(button)});
  }
  function controls(){
    const list=document.getElementById('drawerArticles'),label=list?.closest('.drawer-section')?.querySelector(':scope > .drawer-label');if(!label)return null;
    let box=label.querySelector('.favorites-controls');if(box)return box;
    label.classList.add('favorites-label');const title=document.createElement('span');title.className='favorites-label-text';title.textContent=label.textContent.trim();label.textContent='';label.appendChild(title);
    box=document.createElement('span');box.className='favorites-controls';
    const filterButton=document.createElement('button');filterButton.type='button';filterButton.className='favorites-control favorites-filter';filterButton.innerHTML=icon('star');filterButton.title='Pokaż tylko ulubione';filterButton.setAttribute('aria-label',filterButton.title);filterButton.onclick=()=>{if(filterButton.dataset.longPress)return;if(allActs){setAllActs(false);return}filter=!filter;expanded.clear();persistModes();refresh()};installScopeGesture(filterButton);
    const highlightButton=document.createElement('button');highlightButton.type='button';highlightButton.className='favorites-control favorites-highlight';highlightButton.innerHTML=icon('eye');highlightButton.title='Wyróżnij ulubione';highlightButton.setAttribute('aria-label',highlightButton.title);highlightButton.onclick=()=>{if(filter||allActs)return;highlight=!highlight;persistModes();refresh()};
    box.append(filterButton,highlightButton);label.appendChild(box);return box;
  }
  function ensureEmpty(container,className,text){let empty=container?.querySelector(':scope > .'+className);if(!empty&&container){empty=document.createElement('div');empty.className=className;empty.textContent=text;container.appendChild(empty)}return empty}
  function annotate(article,row){const parts=M.describe(row),nodes=[...article.querySelectorAll(':scope > .unit-body > .subunit')];nodes.forEach((node,index)=>{const part=parts[index];if(part){node.dataset.favoritePart=part.key;node.dataset.favoriteRank=String(part.rank)}});return{parts,nodes}}
  function clearFragmentView(article){article.querySelector(':scope > .favorite-fragment-status')?.remove();article.querySelectorAll('.favorite-omission').forEach(node=>node.remove());article.querySelectorAll('.favorite-part-hidden,.favorite-part-context').forEach(node=>node.classList.remove('favorite-part-hidden','favorite-part-context'));delete article.dataset.favoriteViewKey}
  function applyFragmentView(article,item,row){
    const partial=Array.isArray(item?.parts),isExpanded=expanded.has(article.id),signature=`${filter}|${isExpanded}|${partial?item.parts.join(','):'all'}`;if(article.dataset.favoriteViewKey===signature)return;clearFragmentView(article);article.dataset.favoriteViewKey=signature;if(!filter||!partial)return;
    const {parts,nodes}=annotate(article,row),valid=new Set(parts.map(part=>part.key)),selected=new Set(item.parts.filter(key=>valid.has(key))),visible=isExpanded?valid:M.visibleKeys(parts,selected);
    nodes.forEach((node,index)=>{const key=parts[index]?.key,show=visible.has(key);node.classList.toggle('favorite-part-hidden',!show);node.classList.toggle('favorite-part-context',show&&!selected.has(key))});
    const status=document.createElement('div');status.className='favorite-fragment-status';const copy=document.createElement('span');copy.className='favorite-fragment-copy';copy.innerHTML=icon('star')+'<b>'+(isExpanded?'Pełny artykuł':`Wybrane fragmenty · ${selected.size} z ${parts.length}`)+'</b>';
    const toggle=document.createElement('button');toggle.type='button';toggle.textContent=isExpanded?'Pokaż tylko zapisane':'Rozwiń cały artykuł';toggle.onclick=()=>{if(isExpanded)expanded.delete(article.id);else{expanded.clear();expanded.add(article.id);lastReadingArticle=article.id}delete article.dataset.favoriteViewKey;applyFragmentView(article,item,row)};status.append(copy,toggle);article.querySelector(':scope > .unit-head')?.after(status);if(isExpanded)return;
    let hidden=0;for(let i=0;i<nodes.length;i++){if(nodes[i].classList.contains('favorite-part-hidden')){hidden++;continue}if(hidden){const gap=document.createElement('div');gap.className='favorite-omission';gap.textContent=M.omissionLabel(hidden);nodes[i].before(gap);hidden=0}}if(hidden){const gap=document.createElement('div');gap.className='favorite-omission';gap.textContent=M.omissionLabel(hidden);article.querySelector(':scope > .unit-body')?.appendChild(gap)}
  }
  function groupedFavorites(items){const byAct=new Map();items.forEach(item=>{if(!byAct.has(item.act))byAct.set(item.act,new Set());byAct.get(item.act).add(item.id)});const groups=[];for(const act of DATA||[]){const ids=byAct.get(act[0]);if(!ids?.size)continue;const rows=act[3].filter(row=>ids.has(row[0]));if(rows.length)groups.push({act,rows})}return groups}
  function formatSectionHeading(article,row,actCode){
    const head=article.querySelector(':scope > .unit-head'),section=head?.querySelector(':scope > .section-label'),summary=head?.querySelector(':scope > .editorial-title'),info=globalThis.__EDITORIAL?.sectionInfo?.(row,actCode);
    if(summary){const editorial=row?.[8]!=='s';summary.classList.toggle('is-editorial',editorial);summary.classList.toggle('is-source',!editorial);summary.dataset.titleOrigin=editorial?'editorial':'source';if(editorial)summary.setAttribute('aria-label','Redakcyjne podsumowanie artykułu');else summary.removeAttribute('aria-label')}
    if(!section||!info)return;section.textContent='';const no=document.createElement('span');no.className='section-no';no.textContent=info.prefix;section.appendChild(no);if(info.title){const title=document.createElement('span');title.className='section-title'+(info.generated?' generated':'');title.textContent=info.title;section.appendChild(title)}
  }
  function fitAllLawTitles(){document.querySelectorAll('.favorites-all-law-name').forEach(name=>{const full=name.dataset.full||'',short=name.dataset.short||full,available=name.clientWidth;if(!available||!full)return;if(lawTitleMeasure){lawTitleMeasure.font=getComputedStyle(name).font;const next=lawTitleMeasure.measureText(full).width>available?short:full;if(name.textContent!==next)name.textContent=next}else if(name.textContent!==short)name.textContent=short})}
  function observeAllDrawer(list){if(drawerResizeObserver||typeof ResizeObserver==='undefined')return;drawerResizeObserver=new ResizeObserver(()=>{if(allActs)requestAnimationFrame(fitAllLawTitles)});drawerResizeObserver.observe(list)}
  function syncAllVisibleLaws(){const visible=new Set([...view.querySelectorAll('.favorites-all-act:not([hidden])')].map(section=>section.dataset.favoriteAct));document.querySelectorAll('.quickbar button').forEach(button=>button.classList.toggle('favorites-all-visible',visible.has(button.dataset.act)))}
  function applyAllActVisibility(code,collapsed){
    const main=[...view.querySelectorAll('.favorites-all-act')].find(section=>section.dataset.favoriteAct===code);if(main){main.hidden=collapsed;main.classList.toggle('is-filtered-out',collapsed)}
    const section=[...document.querySelectorAll('#drawerArticles .favorites-all-law')].find(node=>node.dataset.act===code),items=section?.querySelector('.favorites-all-law-items'),title=section?.querySelector('.favorites-all-law-title');section?.classList.toggle('is-collapsed',collapsed);if(items)items.hidden=collapsed;if(title)title.setAttribute('aria-expanded',String(!collapsed));syncAllVisibleLaws();
  }
  function setAllActive(id){
    if(!allActs)return;allActiveId=id||'';
    document.querySelectorAll('#drawerArticles .drawer-article').forEach(link=>link.classList.toggle('active',link.dataset.id===id));
    document.querySelectorAll('#drawerArticles .favorites-all-law').forEach(section=>section.classList.toggle('has-active',!!section.querySelector('.drawer-article.active')));
  }
  function syncAllActive(preferred=''){
    if(!allActs)return;
    const articles=[...view.querySelectorAll('.favorites-all-act:not([hidden]) article.legal-unit')];if(!articles.length){setAllActive('');return}
    let id=preferred&&articles.some(article=>article.id===preferred)?preferred:'';
    if(!id){const y=(document.querySelector('.top')?.getBoundingClientRect().bottom||0)+8;let best=articles[0],distance=Infinity;for(const article of articles){const rect=article.getBoundingClientRect();if(rect.top<=y&&rect.bottom>y){best=article;break}const next=Math.abs(rect.top-y);if(next<distance){distance=next;best=article}}id=best.id}
    setAllActive(id);
  }
  function renderAllMain(items,groups){
    const signature=allViewCycle+'|'+items.map(item=>item.id+':'+(item.parts?.join(',')||'*')).sort().join('|');if(signature===allSignature&&view.classList.contains('favorites-all-view'))return;
    globalThis.__POLICE_STREAM_STOP?.();
    allSignature=signature;let html='<div class="favorites-all-heading"><b>Ulubione</b><span>Wszystkie ustawy</span></div>';
    for(const {act,rows} of groups){const meta=metaFor(act),collapsed=collapsedActs.has(act[0]);html+='<section class="favorites-all-act'+(collapsed?' is-filtered-out':'')+'" data-favorite-act="'+esc(act[0])+'"'+(collapsed?' hidden':'')+'><h2>'+esc(meta[1]||act[1]||act[0])+'</h2>';for(const row of rows)html+=globalThis.__renderLegalArticle(row,act[0]);html+='</section>'}
    view.innerHTML=html;view.classList.add('favorites-all-view');for(const {act,rows} of groups)for(const row of rows){const article=document.getElementById(row[0]);if(article)formatSectionHeading(article,row,act[0])}if(typeof bindLinks==='function')bindLinks();
  }
  function renderAllDrawer(groups){
    const list=document.getElementById('drawerArticles');if(!list)return;
    const signature=allViewCycle+'|'+groups.map(group=>group.act[0]+':'+group.rows.map(row=>row[0]).join(',')).join('|');if(list.dataset.favoritesAllSignature===signature&&list.classList.contains('favorites-all-drawer'))return;
    list.textContent='';list.className='drawer-article-list favorites-all-drawer';list.dataset.favoritesAllSignature=signature;
    for(const {act,rows} of groups){
      const code=act[0],meta=metaFor(act),section=document.createElement('section');section.className='favorites-all-law';section.dataset.act=code;
      const title=document.createElement('button');title.type='button';title.className='favorites-all-law-title';title.setAttribute('aria-expanded',String(!collapsedActs.has(code)));
      const arrow=document.createElement('span');arrow.className='favorites-all-law-arrow';arrow.textContent='▾';arrow.setAttribute('aria-hidden','true');const titleText=document.createElement('span'),fullTitle=meta[1]||act[1]||code,shortTitle=meta[0]||code;titleText.className='favorites-all-law-name';titleText.dataset.full=fullTitle;titleText.dataset.short=shortTitle;titleText.textContent=fullTitle;title.title=fullTitle;title.append(arrow,titleText);
      const items=document.createElement('div');items.className='favorites-all-law-items';items.hidden=collapsedActs.has(code);
      title.onclick=()=>{const collapsed=!collapsedActs.has(code);if(collapsed)collapsedActs.add(code);else collapsedActs.delete(code);const active=document.getElementById(allActiveId),hidesActive=collapsed&&active?.closest('.favorites-all-act')?.dataset.favoriteAct===code;applyAllActVisibility(code,collapsed);requestAnimationFrame(()=>syncAllActive(hidesActive?'':allActiveId))};section.classList.toggle('is-collapsed',collapsedActs.has(code));
      for(const row of rows){const link=document.createElement('a');link.className='drawer-article is-favorite';link.href='#'+row[0];link.dataset.id=row[0];link.dataset.act=code;const number=document.createElement('span');number.className='da-num';number.innerHTML='<span class="da-prefix">A.</span> '+esc(String(row[2]||'').replace(/^Art\.\s*/i,'').replace(/^§\s*/,''));const topic=document.createElement('span');topic.className='da-topic editorial-topic';topic.textContent=row[3]||'';link.append(number,topic);link.onclick=event=>{event.preventDefault();setAllActive(row[0]);if(typeof globalThis.__POLICE_SCROLL_ARTICLE==='function')globalThis.__POLICE_SCROLL_ARTICLE(row[0],true);else document.getElementById(row[0])?.scrollIntoView({block:'start',behavior:'smooth'})};items.appendChild(link)}
      section.append(title,items);list.appendChild(section);
    }
    observeAllDrawer(list);requestAnimationFrame(fitAllLawTitles);
  }
  function syncAllView(items){const groups=groupedFavorites(items),codes=new Set(groups.map(group=>group.act[0]));for(const code of collapsedActs)if(!codes.has(code))collapsedActs.delete(code);document.body.classList.add('favorites-all-acts','act-selected');renderAllMain(items,groups);renderAllDrawer(groups);syncAllVisibleLaws();syncAllActive(allActiveId)}
  function addSwipePanel(article){let panel=article.querySelector(':scope > .favorite-swipe-action');if(panel)return panel;panel=document.createElement('div');panel.className='favorite-swipe-action';panel.setAttribute('aria-hidden','true');panel.inert=true;const cue=document.createElement('span');cue.className='favorite-swipe-cue';cue.textContent='←';cue.setAttribute('aria-hidden','true');const actions=document.createElement('div');actions.className='favorite-swipe-actions';const cancel=document.createElement('button');cancel.type='button';cancel.className='favorite-swipe-cancel';cancel.textContent='Anuluj';cancel.onclick=()=>closeSwipe(false);panel.append(cue,actions,cancel);article.appendChild(panel);return panel}
  function actionButton(className,svg,label,handler){const button=document.createElement('button');button.type='button';button.className=className;button.innerHTML=svg+'<span>'+label+'</span>';button.onclick=handler;return button}
  function positionArticlePopover(pop,anchor){
    const anchorRect=anchor.getBoundingClientRect(),drawerRect=document.body.classList.contains('drawer-open')?document.querySelector('.drawer')?.getBoundingClientRect():null,minLeft=Math.max(6,(drawerRect?.right||0)+4),maxRight=window.innerWidth-6,popRect=pop.getBoundingClientRect(),center=anchorRect.left+anchorRect.width/2,left=Math.max(minLeft,Math.min(maxRight-popRect.width,center-popRect.width/2));let top=anchorRect.bottom+8,above=false;if(top+popRect.height>window.innerHeight-8){top=Math.max(8,anchorRect.top-popRect.height-8);above=true}pop.style.left=left+'px';pop.style.top=top+'px';pop.style.setProperty('--article-caret-x',Math.max(14,Math.min(popRect.width-14,center-left))+'px');pop.classList.toggle('above',above);pop.classList.add('show');
  }
  function showArticlePopover(anchor,article){
    closeScopePopover();closeArticlePopover();const item=itemFor(article.id),row=rowFor(article.id);if(!item||!row)return;
    const pop=document.createElement('div');pop.className='favorite-article-popover';pop.setAttribute('role','menu');pop.setAttribute('aria-label','Akcje ulubionego artykułu');const actions=document.createElement('div');actions.className='favorite-article-menu-actions',editable=M.describe(row).length>1;
    if(editable){const edit=actionButton('favorite-article-menu-button favorite-article-menu-edit',icon('edit'),'Edytuj',()=>{closeArticlePopover();startEditor(article)});edit.setAttribute('role','menuitem');actions.appendChild(edit)}
    const remove=actionButton('favorite-article-menu-button favorite-article-menu-remove',icon('trash'),'Usuń z ulubionych',()=>removeFavorite(article.id));remove.setAttribute('role','menuitem');actions.appendChild(remove);pop.appendChild(actions);document.body.appendChild(pop);requestAnimationFrame(()=>positionArticlePopover(pop,anchor));
  }
  function installArticleActionGesture(button,article){
    if(button.dataset.favoriteActionGesture)return;button.dataset.favoriteActionGesture='1';let timer=0,long=false,start=null;const clear=()=>{clearTimeout(timer);timer=0};const enabled=()=>filter&&document.body.classList.contains('drawer-open')&&!!itemFor(article.id);
    button.addEventListener('pointerdown',event=>{if(!enabled()||(event.pointerType==='mouse'&&event.button!==0))return;event.preventDefault();long=false;start={x:event.clientX,y:event.clientY};clear();try{button.setPointerCapture(event.pointerId)}catch(_){}timer=setTimeout(()=>{timer=0;long=true;button.dataset.favoriteActionLong='1';showArticlePopover(button,article);navigator.vibrate?.(12)},340)});
    button.addEventListener('pointermove',event=>{if(!timer||!start)return;if(Math.abs(event.clientX-start.x)>30||Math.abs(event.clientY-start.y)>34)clear()});
    button.addEventListener('pointerup',event=>{event.preventDefault();clear();start=null;if(long){const target=document.elementFromPoint(event.clientX,event.clientY)?.closest('.favorite-article-menu-button');if(target)target.click();setTimeout(()=>delete button.dataset.favoriteActionLong,0)}});
    button.addEventListener('pointercancel',()=>{clear();start=null});button.addEventListener('click',event=>{event.preventDefault();event.stopImmediatePropagation()},true);button.addEventListener('contextmenu',event=>{if(!enabled())return;event.preventDefault();event.stopImmediatePropagation();showArticlePopover(button,article)});
  }
  function syncArticleStar(article,on){const button=article.querySelector(':scope > .unit-head > .unit-star');if(!button)return;button.classList.toggle('on',on);button.textContent=on?'★':'☆';button.title=on?'Artykuł w ulubionych':'Dodaj przez przesunięcie artykułu w lewo';button.setAttribute('aria-label',button.title);button.setAttribute('aria-pressed',String(on));if(on)installArticleActionGesture(button,article)}
  function updateSwipePanel(article,on){const panel=addSwipePanel(article),actions=panel.querySelector('.favorite-swipe-actions'),editable=on&&M.describe(rowFor(article.id)||[]).length>1,state=(on?'saved':'new')+':'+editable;if(actions.dataset.state===state)return;actions.dataset.state=state;actions.textContent='';if(!on){actions.append(actionButton('favorite-swipe-toggle',icon('star'),'Dodaj do<br>ulubionych',()=>addFavorite(article.id)));return}if(editable)actions.append(actionButton('favorite-swipe-edit',icon('edit'),'Edytuj wybór',()=>startEditor(article)));actions.append(actionButton('favorite-swipe-remove',icon('trash'),'Usuń z<br>ulubionych',()=>removeFavorite(article.id)))}
  function unlockSwipeScroll(){document.body.classList.remove('favorite-swipe-active','favorite-swipe-nav-hidden')}
  function clearSwipeBalance(article){
    if(!article?.classList.contains('favorite-swipe-balanced'))return;
    const anchor=article.querySelector(':scope > .unit-head'),top=anchor?.getBoundingClientRect().top;
    article.classList.remove('favorite-swipe-balanced');article.style.removeProperty('--favorite-balance-space');
    if(Number.isFinite(top)){const next=anchor.getBoundingClientRect().top,delta=next-top;if(Math.abs(delta)>.5)window.scrollBy(0,delta)}
  }
  function finishSwipeClose(article,panel){article?.classList.remove('favorite-swipe-closing');clearSwipeBalance(article);panel?.classList.remove('is-compact');panel?.style.removeProperty('--favorite-panel-right');panel?.style.removeProperty('--favorite-panel-top');panel?.style.removeProperty('--favorite-panel-height');unlockSwipeScroll()}
  function closeSwipe(immediate=false){clearTimeout(swipeCloseTimer);if(!activeArticle){if(immediate)unlockSwipeScroll();return}const article=activeArticle,panel=article.querySelector(':scope > .favorite-swipe-action');activeArticle=null;article.classList.remove('favorite-swipe-open','favorite-swiping');article.style.removeProperty('--favorite-swipe-x');panel?.setAttribute('aria-hidden','true');if(panel)panel.inert=true;if(immediate){finishSwipeClose(article,panel);return}article.classList.add('favorite-swipe-closing');swipeCloseTimer=setTimeout(()=>finishSwipeClose(article,panel),190)}
  function swipeViewport(){const visual=window.visualViewport,visualTop=visual?.offsetTop||0,visualBottom=visualTop+(visual?.height||window.innerHeight),headerBottom=document.querySelector('.top')?.getBoundingClientRect().bottom||72;return{top:Math.max(visualTop+6,headerBottom+7),bottom:visualBottom-7}}
  function swipeNavTop(bounds){const nav=document.querySelector('.article-pager');if(!nav||getComputedStyle(nav).display==='none'||getComputedStyle(nav).visibility==='hidden')return null;const rect=nav.getBoundingClientRect();return rect.height>0&&rect.top>bounds.top?Math.min(bounds.bottom,rect.top-7):null}
  function swipeScrollDelta(rect,top,bottom,height){if(rect.top>bottom-height)return rect.top-(bottom-height);if(rect.bottom<top+height)return rect.bottom-(top+height);return 0}
  function balanceSwipeArticle(article,height){let rect=article.getBoundingClientRect();const missing=Math.max(0,height-rect.height);if(missing>.5){article.classList.add('favorite-swipe-balanced');article.style.setProperty('--favorite-balance-space',Math.ceil(missing/2)+'px');rect=article.getBoundingClientRect()}return rect}
  function openSwipe(article){
    closeSwipe(true);activeArticle=article;const on=!!itemFor(article.id);updateSwipePanel(article,on);const panel=article.querySelector(':scope > .favorite-swipe-action');if(!panel)return;
    const bounds=swipeViewport(),buttonCount=panel.querySelectorAll('.favorite-swipe-actions button').length||1,preferred=buttonCount>1?244:184,withoutNav=Math.max(120,bounds.bottom-bounds.top),minimum=Math.min(preferred,withoutNav),navTop=swipeNavTop(bounds);let rect=balanceSwipeArticle(article,minimum),withNav=navTop||bounds.bottom;
    const deltaWith=swipeScrollDelta(rect,bounds.top,withNav,minimum),deltaWithout=swipeScrollDelta(rect,bounds.top,bounds.bottom,minimum),hideNav=!!navTop&&((withNav-bounds.top<minimum&&withoutNav>=minimum)||(Math.abs(deltaWith)>.5&&Math.abs(deltaWithout)<=.5)),viewBottom=hideNav?bounds.bottom:withNav,delta=swipeScrollDelta(rect,bounds.top,viewBottom,minimum);
    if(Math.abs(delta)>.5){window.scrollBy(0,delta);rect=article.getBoundingClientRect()}
    const naturalTop=Math.max(bounds.top,rect.top),naturalBottom=Math.min(viewBottom,rect.bottom),available=Math.max(120,viewBottom-bounds.top);let top=naturalTop,height=naturalBottom-naturalTop;
    if(height<minimum){height=Math.min(minimum,available);const middle=Math.max(bounds.top,Math.min(viewBottom,(Math.max(rect.top,bounds.top)+Math.min(rect.bottom,viewBottom))/2));top=Math.max(bounds.top,Math.min(viewBottom-height,middle-height/2))}
    document.body.classList.add('favorite-swipe-active');document.body.classList.toggle('favorite-swipe-nav-hidden',hideNav);panel.classList.toggle('is-compact',height<(buttonCount>1?260:205));panel.style.setProperty('--favorite-panel-right',Math.max(0,window.innerWidth-rect.right)+'px');panel.style.setProperty('--favorite-panel-top',top+'px');panel.style.setProperty('--favorite-panel-height',height+'px');article.classList.add('favorite-swipe-open');panel.setAttribute('aria-hidden','false');panel.inert=false;
  }
  function setEditorButtons(){if(!editor)return;const {parts,selected,article}=editor;article.querySelectorAll('.favorite-part-toggle').forEach(button=>{const index=Number(button.dataset.index),group=M.groupKeys(parts,index),count=group.filter(key=>selected.has(key)).length,state=count===0?'off':count===group.length?'on':'mixed';button.dataset.state=state;button.setAttribute('aria-checked',state==='mixed'?'mixed':String(state==='on'));button.title=state==='on'?'Odznacz ten fragment':'Zaznacz ten fragment'});const saveButton=article.querySelector('.favorite-editor-save');if(saveButton)saveButton.disabled=selected.size===0;const helper=article.querySelector('.favorite-editor-helper');if(helper)helper.textContent=selected.size?'Odznacz fragmenty, których nie chcesz zapisywać.':'Wybierz co najmniej jeden fragment.'}
  function toggleEditorPart(index){if(!editor)return;const group=M.groupKeys(editor.parts,index),all=group.every(key=>editor.selected.has(key));group.forEach(key=>all?editor.selected.delete(key):editor.selected.add(key));setEditorButtons()}
  function captureEditorAnchor(article,selected){const top=(document.querySelector('.top')?.getBoundingClientRect().bottom||0)+8,nodes=[...article.querySelectorAll(':scope > .unit-body > .subunit')],kept=nodes.filter(item=>!selected||selected.has(item.dataset.favoritePart)),visible=kept.find(item=>{const rect=item.getBoundingClientRect();return rect.bottom>top&&rect.top<window.innerHeight}),node=visible||kept.sort((a,b)=>Math.abs(a.getBoundingClientRect().top-top)-Math.abs(b.getBoundingClientRect().top-top))[0]||article;return{articleId:article.id,nodeId:node.id||'',part:node.dataset.favoritePart||'',top:node.getBoundingClientRect().top}}
  function restoreEditorAnchor(anchor){const article=document.getElementById(anchor.articleId);if(!article)return;let node=anchor.nodeId?document.getElementById(anchor.nodeId):null;if(!node&&anchor.part)node=article.querySelector('[data-favorite-part="'+CSS.escape(anchor.part)+'"]');if(!node||getComputedStyle(node).display==='none')node=article;const delta=node.getBoundingClientRect().top-anchor.top;if(Math.abs(delta)>.5)window.scrollBy(0,delta)}
  function exitEditor(restoreDrawer=true,useCurrentSelection=false){if(!editor)return;const {article,wasDrawerOpen,selected,initialSelected}=editor,anchor=captureEditorAnchor(article,useCurrentSelection?selected:initialSelected);article.querySelector(':scope > .favorite-editor-bar')?.remove();article.querySelectorAll('.favorite-part-toggle').forEach(button=>button.remove());article.querySelectorAll('.favorite-editor-has-marker,.favorite-editor-no-marker').forEach(node=>node.classList.remove('favorite-editor-has-marker','favorite-editor-no-marker'));article.closest('.favorites-all-act')?.classList.remove('favorite-edit-act');article.classList.remove('favorite-edit-target');document.body.classList.remove('favorite-editing');editor=null;refresh();const finish=()=>requestAnimationFrame(()=>requestAnimationFrame(()=>restoreEditorAnchor(anchor)));if(restoreDrawer&&wasDrawerOpen)setTimeout(()=>{document.getElementById('hamburger')?.click();setTimeout(finish,90)},40);else finish()}
  function saveEditor(){if(!editor||!editor.selected.size)return;const items=read(),index=items.findIndex(item=>item.id===editor.article.id);if(index<0)return;const all=editor.parts.map(part=>part.key),selected=all.filter(key=>editor.selected.has(key));if(selected.length===all.length)delete items[index].parts;else items[index].parts=selected;items[index].favoriteVersion=2;save(items);expanded.delete(editor.article.id);exitEditor(true,true);syncLegacy()}
  function startEditor(article){
    const item=itemFor(article.id),row=rowFor(article.id);if(!item||!row||M.describe(row).length<=1)return;closeArticlePopover();closeSwipe(true);const wasDrawerOpen=document.body.classList.contains('drawer-open');if(wasDrawerOpen)document.querySelector('.drawer-expand')?.click();clearFragmentView(article);const {parts,nodes}=annotate(article,row),valid=new Set(parts.map(part=>part.key)),selected=new Set(Array.isArray(item.parts)?item.parts.filter(key=>valid.has(key)):parts.map(part=>part.key));editor={article,row,parts,nodes,selected,initialSelected:new Set(selected),wasDrawerOpen};document.body.classList.add('favorite-editing','act-selected');article.closest('.favorites-all-act')?.classList.add('favorite-edit-act');article.classList.add('favorite-edit-target');
    const bar=document.createElement('div');bar.className='favorite-editor-bar';const top=document.createElement('div');top.className='favorite-editor-top';const cancel=document.createElement('button');cancel.type='button';cancel.className='favorite-editor-cancel';cancel.textContent='Anuluj';cancel.onclick=()=>exitEditor();const title=document.createElement('b');title.textContent='Edytujesz ulubione · '+row[2];const saveButton=document.createElement('button');saveButton.type='button';saveButton.className='favorite-editor-save';saveButton.textContent='Zapisz';saveButton.onclick=saveEditor;const helper=document.createElement('div');helper.className='favorite-editor-helper';top.append(cancel,title,saveButton);bar.append(top,helper);article.prepend(bar);
    nodes.forEach((node,index)=>{const button=document.createElement('button');button.type='button';button.className='favorite-part-toggle';button.dataset.index=String(index);button.setAttribute('role','checkbox');button.setAttribute('aria-label','Wybierz '+(parts[index].marker||'tekst główny'));button.onclick=()=>toggleEditorPart(index);node.prepend(button);node.classList.add(node.querySelector(':scope > .marker')?'favorite-editor-has-marker':'favorite-editor-no-marker')});setEditorButtons();requestAnimationFrame(()=>article.scrollIntoView({block:'start',behavior:'smooth'}));
  }
  function refresh(){
    if(editor)return;const items=read(),map=new Map(items.map(item=>[item.id,item])),set=new Set(map.keys()),box=controls(),highlightDisabled=filter||allActs;if(allActs)syncAllView(items);document.body.classList.toggle('favorites-filter-on',filter);document.body.classList.toggle('favorites-highlight-on',highlight&&!highlightDisabled);const filterButton=box?.querySelector('.favorites-filter'),highlightButton=box?.querySelector('.favorites-highlight');filterButton?.classList.toggle('on',filter);filterButton?.classList.toggle('all-acts',allActs);highlightButton?.classList.toggle('on',highlight&&!highlightDisabled);if(highlightButton){highlightButton.disabled=highlightDisabled;highlightButton.setAttribute('aria-disabled',String(highlightDisabled));highlightButton.title=highlightDisabled?'Wyróżnienie jest dostępne poza widokiem samych ulubionych':'Wyróżnij ulubione'}filterButton?.setAttribute('aria-pressed',String(filter));filterButton?.setAttribute('aria-label',allActs?'Ulubione ze wszystkich ustaw':'Pokaż tylko ulubione');highlightButton?.setAttribute('aria-pressed',String(highlight&&!highlightDisabled));
    const articles=[...view.querySelectorAll('article.legal-unit')];articles.forEach(article=>{const item=map.get(article.id),on=!!item,row=rowFor(article.id);article.classList.toggle('is-favorite',on);article.classList.toggle('is-partial-favorite',Array.isArray(item?.parts));syncArticleStar(article,on);if(article.querySelector(':scope > .favorite-swipe-action'))updateSwipePanel(article,on);if(row&&on)applyFragmentView(article,item,row);else clearFragmentView(article)});
    document.querySelectorAll('.toc-link[href^="#"]').forEach(link=>{const id=link.getAttribute('href')?.slice(1)||'';link.classList.toggle('is-favorite',set.has(id))});
    const drawerRows=[...document.querySelectorAll('.drawer-article')];drawerRows.forEach(row=>{const item=map.get(row.dataset.id);row.classList.toggle('is-favorite',!!item);row.classList.toggle('is-partial-favorite',Array.isArray(item?.parts))});document.querySelectorAll('.drawer-chapter').forEach(chapter=>chapter.classList.toggle('favorites-chapter-empty',filter&&!chapter.querySelector('.drawer-article.is-favorite')));
    const currentCount=articles.filter(article=>set.has(article.id)).length,mainEmpty=ensureEmpty(view,'favorites-empty-main',allActs?'Brak ulubionych artykułów.':'Brak ulubionych artykułów w tej ustawie.');if(mainEmpty)mainEmpty.hidden=!filter||currentCount>0;const list=document.getElementById('drawerArticles'),drawerEmpty=ensureEmpty(list,'favorites-empty-drawer',allActs?'Brak ulubionych artykułów.':'Brak ulubionych w tej ustawie.');if(drawerEmpty)drawerEmpty.hidden=!filter||currentCount>0;
  }
  function swipeTarget(target,x){if(editor||document.body.classList.contains('drawer-open')||target.closest('a,button,input,summary,.navrefs,.favorite-swipe-action'))return null;const article=target.closest('article.legal-unit');if(!article)return null;if(article===activeArticle)return{article,closing:true};const rect=article.getBoundingClientRect();return x>=rect.right-Math.min(54,rect.width*.14)?{article,closing:false}:null}
  function swipeOffset(dx,closing){return Math.max(-112,Math.min(0,closing?dx-112:dx))}
  let suppressSwipeClickUntil=0;
  function updateSwipeDrag(state,dx){const offset=swipeOffset(dx,state.closing);state.article.classList.add('favorite-swiping');state.article.style.setProperty('--favorite-swipe-x',offset+'px');if(state.closing)state.article.style.setProperty('--favorite-panel-x',offset+112+'px')}
  function clearSwipeDrag(state){state?.article.classList.remove('favorite-swiping');state?.article.style.removeProperty('--favorite-swipe-x');state?.article.style.removeProperty('--favorite-panel-x')}
  view.addEventListener('touchstart',event=>{if(event.touches.length!==1)return;const point=event.touches[0],state=swipeTarget(event.target,point.clientX);if(!state)return;event.stopPropagation();touch={...state,x:point.clientX,y:point.clientY,axis:null}},{capture:true,passive:true});
  view.addEventListener('touchmove',event=>{if(!touch||event.touches.length!==1)return;event.stopPropagation();const point=event.touches[0],dx=point.clientX-touch.x,dy=point.clientY-touch.y;if(!touch.axis&&Math.max(Math.abs(dx),Math.abs(dy))>10)touch.axis=Math.abs(dx)>Math.abs(dy)*1.15?'x':'y';if(touch.axis==='x'){event.preventDefault();updateSwipeDrag(touch,dx)}},{capture:true,passive:false});
  view.addEventListener('touchend',event=>{if(!touch)return;event.stopPropagation();const point=event.changedTouches[0],state=touch,dx=point?point.clientX-state.x:0,axis=state.axis;touch=null;clearSwipeDrag(state);if(axis==='x')suppressSwipeClickUntil=Date.now()+450;if(state.closing){if(axis==='x'&&dx>52)closeSwipe();return}if(axis==='x'&&dx<-52)openSwipe(state.article)},{capture:true,passive:true});
  view.addEventListener('touchcancel',()=>{if(touch){touch.article.classList.remove('favorite-swiping');touch.article.style.removeProperty('--favorite-swipe-x')}touch=null},{capture:true,passive:true});
  function blockSwipeScroll(event){if(document.body.classList.contains('favorite-swipe-active'))event.preventDefault()}
  document.addEventListener('touchmove',blockSwipeScroll,{capture:true,passive:false});window.addEventListener('wheel',blockSwipeScroll,{passive:false});
  view.addEventListener('pointerdown',event=>{if(event.pointerType==='touch'||event.button!==0)return;const state=swipeTarget(event.target,event.clientX);if(!state)return;pointer={...state,x:event.clientX,y:event.clientY,id:event.pointerId,axis:null};state.article.setPointerCapture?.(event.pointerId)});view.addEventListener('pointermove',event=>{if(!pointer||event.pointerId!==pointer.id)return;const dx=event.clientX-pointer.x,dy=event.clientY-pointer.y;if(!pointer.axis&&Math.max(Math.abs(dx),Math.abs(dy))>10)pointer.axis=Math.abs(dx)>Math.abs(dy)*1.15?'x':'y';if(pointer.axis!=='x')return;event.preventDefault();updateSwipeDrag(pointer,dx)});view.addEventListener('pointerup',event=>{if(!pointer||event.pointerId!==pointer.id)return;const state=pointer,dx=event.clientX-state.x;pointer=null;clearSwipeDrag(state);if(state.axis==='x')suppressSwipeClickUntil=Date.now()+450;if(state.closing){if(state.axis==='x'&&dx>52)closeSwipe();return}if(state.axis==='x'&&dx<-52)openSwipe(state.article)});view.addEventListener('pointercancel',event=>{if(!pointer||event.pointerId!==pointer.id)return;clearSwipeDrag(pointer);pointer=null});
  document.getElementById('quickbar')?.addEventListener('click',event=>{if(!allActs)return;const button=event.target.closest('button[data-act]');if(!button)return;event.preventDefault();event.stopImmediatePropagation();setAllActs(false,button.dataset.act)},true);
  let refreshQueued=false;function scheduleRefresh(){if(refreshQueued)return;refreshQueued=true;requestAnimationFrame(()=>{refreshQueued=false;refresh()})}
  document.addEventListener('click',event=>{if(!event.target.closest('.favorites-scope-popover,.favorites-filter'))closeScopePopover();if(!event.target.closest('.favorite-article-popover,.unit-star'))closeArticlePopover();if(activeArticle&&Date.now()>=suppressSwipeClickUntil&&!event.target.closest('.favorite-swipe-action'))closeSwipe(false)});window.addEventListener('storage',event=>{if(event.key===KEY)scheduleRefresh()});window.addEventListener('police-law-favorites-change',scheduleRefresh);window.addEventListener('police-law-rendered',scheduleRefresh);window.addEventListener('police-law-articles-rendered',scheduleRefresh);window.addEventListener('police-law-toc-rendered',scheduleRefresh);window.addEventListener('police-law-drawer-rendered',scheduleRefresh);window.addEventListener('police-law-stars-ready',scheduleRefresh);
  window.addEventListener('scroll',()=>{closeScopePopover();closeArticlePopover();if(allActs&&!activeQueued){activeQueued=true;requestAnimationFrame(()=>{activeQueued=false;syncAllActive()})}if(!expanded.size||editor)return;const y=(document.querySelector('.top')?.getBoundingClientRect().height||0)+12;let current='';for(const article of view.querySelectorAll('article.legal-unit')){const rect=article.getBoundingClientRect();if(rect.top<=y&&rect.bottom>y){current=article.id;break}}if(current&&lastReadingArticle&&current!==lastReadingArticle){expanded.clear();document.querySelectorAll('.legal-unit').forEach(article=>delete article.dataset.favoriteViewKey);refresh()}lastReadingArticle=current||lastReadingArticle},{passive:true});
  refresh();
})();
