(function(){
let drawer,backdrop,articleList,actsBox,headSub,toast,bottomNav,bmBtn,touchStart,toastTimer,lastActCode=null,wide=false;
const BMKEY='police-law-bookmarks-v1';
function ready(){try{return Array.isArray(DATA)&&DATA.length&&ACT&&ACT[3]&&typeof jump==='function'}catch(_){return false}}
function meta(code){try{return META[code]||[code,actBy(code)?.[1]||code,'']}catch(_){return[code,code,'']}}
function articles(){return ACT?.[3]||[]}
function topOffset(){return (document.querySelector('.top')?.getBoundingClientRect().height||0)+8}
function currentIndex(){const rows=[...document.querySelectorAll('#actview .legal-unit')];if(!rows.length)return 0;const y=topOffset()+8;let best=0,d=Infinity;rows.forEach((el,i)=>{const r=el.getBoundingClientRect();if(r.top<=y&&r.bottom>y){best=i;d=0}else if(d){const x=Math.abs(r.top-y);if(x<d){d=x;best=i}}});return Math.min(best,articles().length-1)}
function currentRow(){return articles()[currentIndex()]||articles()[0]}
function showToast(s){if(!toast)return;toast.textContent=s;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),900)}
function scrollArticleTop(id){const el=document.getElementById(id);if(!el)return;const y=window.scrollY+el.getBoundingClientRect().top-topOffset();window.scrollTo({top:Math.max(0,y),behavior:'smooth'});setTimeout(()=>window.scrollTo({top:Math.max(0,window.scrollY+el.getBoundingClientRect().top-topOffset()),behavior:'auto'}),380)}
function gotoId(id){history.replaceState(null,'','#'+id);jump(id,false);requestAnimationFrame(()=>scrollArticleTop(id));setTimeout(updateUI,430)}
function goArticle(step){const a=articles(),i=currentIndex(),n=i+step;if(n<0){showToast('To pierwszy artykuł');return}if(n>=a.length){showToast('To ostatni artykuł');return}closeDrawer();results?.classList.remove('show');gotoId(a[n][0]);showToast((step>0?'→ ':'← ')+(a[n][2]||''))}
function getBM(){try{return JSON.parse(localStorage.getItem(BMKEY)||'[]')}catch(_){return[]}}
function setBM(x){localStorage.setItem(BMKEY,JSON.stringify(x))}
function isBM(id){return getBM().some(x=>x.id===id)}
function toggleBM(){const r=currentRow();if(!r)return;let b=getBM(),i=b.findIndex(x=>x.id===r[0]);if(i>=0){b.splice(i,1);showToast('Usunięto z zapisanych')}else{b.unshift({id:r[0],act:ACT[0],num:r[2],topic:r[3]||''});showToast('Zapisano '+r[2])}setBM(b);populateDrawer();updateUI()}
function openBookmark(x){if(!actBy(x.act))return;renderAct(x.act,null,false);setTimeout(()=>{gotoId(x.id);populateDrawer()},70);closeDrawer()}
function sectionName(r){return String(r?.[1]||'').trim()||'Pozostałe'}
function populateDrawer(){if(!ready()||!drawer)return;headSub.textContent=meta(ACT[0])[1];actsBox.innerHTML='';for(const A of DATA){const m=meta(A[0]),b=document.createElement('button');b.className='drawer-act'+(A[0]===ACT[0]?' on':'');b.type='button';b.innerHTML='<span class="act-ico">§</span><span>'+esc(m[0])+'</span>';b.title=m[1];b.onclick=()=>{renderAct(A[0],null,false);setTimeout(()=>{populateDrawer();gotoId(ACT[3][0]?.[0])},70)};actsBox.appendChild(b)}
const bmBox=drawer.querySelector('#drawerBookmarks'),bms=getBM();bmBox.innerHTML='';drawer.querySelector('#bmSection').hidden=!bms.length;bms.forEach(x=>{const b=document.createElement('button');b.className='bookmark-row';b.innerHTML='<span class="bm-ico">★</span><span><b>'+esc(meta(x.act)[0]+' · '+x.num)+'</b><small>'+esc(x.topic||'Bez tytułu')+'</small></span>';b.onclick=()=>openBookmark(x);bmBox.appendChild(b)});
articleList.innerHTML='';let sec='';for(const R of articles()){const s=sectionName(R);if(s!==sec){sec=s;const h=document.createElement('details');h.className='drawer-chapter';h.open=true;h.innerHTML='<summary><span class="chapter-ico">▾</span>'+esc(s)+'</summary><div class="chapter-items"></div>';articleList.appendChild(h)}const box=articleList.lastElementChild.querySelector('.chapter-items'),a=document.createElement('a');a.className='drawer-article';a.href='#'+R[0];a.dataset.id=R[0];a.innerHTML='<span class="da-num">'+esc(R[2])+'</span><span class="da-topic">'+esc(R[3]||'')+'</span>';a.onclick=e=>{e.preventDefault();closeDrawer();gotoId(R[0])};box.appendChild(a)}lastActCode=ACT[0];updateUI()}
function updateUI(){if(!ready())return;const r=currentRow(),i=currentIndex();document.querySelectorAll('.drawer-article').forEach(a=>a.classList.toggle('active',a.dataset.id===r?.[0]));if(bmBtn&&r){const on=isBM(r[0]);bmBtn.classList.toggle('on',on);bmBtn.title=(on?'Usuń zakładkę: ':'Zapisz: ')+(r[2]||'');bmBtn.setAttribute('aria-label',bmBtn.title)}if(bottomNav){const prev=articles()[i-1],next=articles()[i+1];bottomNav.querySelector('.prev').disabled=!prev;bottomNav.querySelector('.next').disabled=!next;bottomNav.querySelector('.prev span').textContent=prev?prev[2]:'—';bottomNav.querySelector('.next span').textContent=next?next[2]:'—'}}
function syncHamburger(){const hb=document.getElementById('hamburger');if(!hb)return;const on=!!drawer?.classList.contains('open');hb.setAttribute('aria-label',on?'Zamknij menu':'Otwórz menu');hb.setAttribute('aria-expanded',on?'true':'false')}
function openDrawer(){populateDrawer();drawer.classList.add('open');backdrop.classList.add('open');document.body.classList.add('drawer-open');drawer.setAttribute('aria-hidden','false');syncHamburger()}
function closeDrawer(){if(!drawer)return;drawer.classList.remove('open');backdrop.classList.remove('open');document.body.classList.remove('drawer-open');drawer.setAttribute('aria-hidden','true');syncHamburger()}
function toggleWide(){wide=!wide;document.body.classList.toggle('drawer-wide',wide);const b=drawer?.querySelector('.drawer-expand');if(b){b.textContent=wide?'↙':'↗';b.title=wide?'Zwęź menu':'Rozszerz menu'}}
function showBookmarks(){openDrawer();setTimeout(()=>{const s=drawer.querySelector('#bmSection');if(!s.hidden)s.scrollIntoView({block:'start',behavior:'smooth'});else showToast('Brak zapisanych artykułów')},80)}
function build(){if(document.getElementById('hamburger'))return;const topline=document.querySelector('.topline');if(!topline)return;const hb=document.createElement('button');hb.id='hamburger';hb.className='hamburger';hb.type='button';hb.setAttribute('aria-label','Otwórz menu');hb.setAttribute('aria-expanded','false');hb.innerHTML='<span></span><span></span><span></span>';hb.onclick=()=>drawer?.classList.contains('open')?closeDrawer():openDrawer();topline.prepend(hb);
backdrop=document.createElement('div');backdrop.className='drawer-backdrop';backdrop.onclick=closeDrawer;drawer=document.createElement('aside');drawer.className='drawer';drawer.setAttribute('aria-hidden','true');drawer.innerHTML='<div class="drawer-head"><div class="drawer-head-text"><b>Policyjna baza prawa</b><small id="drawerHeadSub"></small></div><div class="drawer-tools"><button class="drawer-bookmarks" type="button" title="Zapisane">★</button><button class="drawer-expand" type="button" title="Wróć do pełnego widoku">↘</button><button class="drawer-close" type="button" aria-label="Zamknij">×</button></div></div><div class="drawer-scroll"><section class="drawer-section"><div class="drawer-label">Akty prawne</div><div class="drawer-acts" id="drawerActs"></div></section><section class="drawer-section" id="bmSection" hidden><div class="drawer-label">★ Zapisane</div><div id="drawerBookmarks"></div></section><section class="drawer-section"><div class="drawer-label">Spis treści</div><div class="drawer-article-list" id="drawerArticles"></div></section></div><div class="split-handle" role="separator" aria-label="Zmień szerokość spisu treści" aria-valuemin="35" aria-valuemax="55" aria-valuenow="45"><span></span></div>';
toast=document.createElement('div');toast.className='swipe-toast';bottomNav=document.createElement('nav');bottomNav.className='article-pager';bottomNav.innerHTML='<button class="prev"><b>‹</b><small>Poprzedni</small><span></span></button><button class="next"><small>Następny</small><span></span><b>›</b></button>';document.body.append(backdrop,drawer,toast,bottomNav);drawer.querySelector('.drawer-close').onclick=closeDrawer;drawer.querySelector('.drawer-expand').onclick=closeDrawer;drawer.querySelector('.drawer-bookmarks').onclick=showBookmarks;actsBox=drawer.querySelector('#drawerActs');articleList=drawer.querySelector('#drawerArticles');headSub=drawer.querySelector('#drawerHeadSub');bottomNav.querySelector('.prev').onclick=()=>goArticle(-1);bottomNav.querySelector('.next').onclick=()=>goArticle(1);populateDrawer();syncHamburger();
const handle=drawer.querySelector('.split-handle');let drag=false;const setSplit=x=>{const pct=Math.max(35,Math.min(55,x/window.innerWidth*100));document.documentElement.style.setProperty('--drawerW',pct+'vw');handle.setAttribute('aria-valuenow',Math.round(pct))};handle.addEventListener('pointerdown',e=>{drag=true;handle.setPointerCapture(e.pointerId);document.body.classList.add('split-dragging');e.preventDefault()});handle.addEventListener('pointermove',e=>{if(drag)setSplit(e.clientX)});handle.addEventListener('pointerup',e=>{if(!drag)return;drag=false;document.body.classList.remove('split-dragging');try{localStorage.setItem('police-law-split',parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--drawerW'))||45)}catch(_){};try{handle.releasePointerCapture(e.pointerId)}catch(_){}});try{const saved=parseFloat(localStorage.getItem('police-law-split'));if(saved>=35&&saved<=55)document.documentElement.style.setProperty('--drawerW',saved+'vw')}catch(_){}
let ticking=false;window.addEventListener('scroll',()=>{if(ticking)return;ticking=true;requestAnimationFrame(()=>{ticking=false;updateUI()})},{passive:true});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDrawer()});const view=document.getElementById('actview');new MutationObserver(()=>{if(ready()&&ACT[0]!==lastActCode)populateDrawer()}).observe(view,{childList:true});
const observer=new MutationObserver(()=>installArticleBookmark());observer.observe(view,{childList:true,subtree:true});installArticleBookmark();
function installArticleBookmark(){const head=view.querySelector('.act-head');if(!head||head.querySelector('.article-bookmark'))return;bmBtn=document.createElement('button');bmBtn.className='article-bookmark';bmBtn.type='button';bmBtn.innerHTML='<span>☆</span><small>Zapisz artykuł</small>';bmBtn.onclick=toggleBM;head.appendChild(bmBtn);updateUI()}
document.addEventListener('touchstart',e=>{if(e.touches.length!==1||drawer.classList.contains('open')){touchStart=null;return}if(e.target.closest('input,button,a,summary,.quickbar,.navrefs')){touchStart=null;return}const p=e.touches[0];touchStart={x:p.clientX,y:p.clientY,t:Date.now(),axis:null}},{passive:true});document.addEventListener('touchmove',e=>{if(!touchStart||e.touches.length!==1)return;const p=e.touches[0],dx=p.clientX-touchStart.x,dy=p.clientY-touchStart.y;if(!touchStart.axis&&Math.max(Math.abs(dx),Math.abs(dy))>14)touchStart.axis=Math.abs(dx)>Math.abs(dy)*1.12?'x':'y';if(touchStart.axis==='x')e.preventDefault()},{passive:false});document.addEventListener('touchend',e=>{if(!touchStart||!e.changedTouches.length)return;const p=e.changedTouches[0],dx=p.clientX-touchStart.x,dy=p.clientY-touchStart.y,dt=Date.now()-touchStart.t,axis=touchStart.axis;touchStart=null;if(axis!=='x'||dt>1000||Math.abs(dx)<52||Math.abs(dx)<Math.abs(dy)*1.15)return;goArticle(dx<0?1:-1)},{passive:true});document.addEventListener('touchcancel',()=>touchStart=null,{passive:true});let ds=null;drawer.addEventListener('touchstart',e=>{if(e.target.closest('.split-handle'))return;if(e.touches.length===1)ds={x:e.touches[0].clientX,y:e.touches[0].clientY}},{passive:true});drawer.addEventListener('touchend',e=>{if(!ds||!e.changedTouches.length)return;const p=e.changedTouches[0],dx=p.clientX-ds.x,dy=p.clientY-ds.y;ds=null;if(dx<-55&&Math.abs(dx)>Math.abs(dy)*1.25)closeDrawer()},{passive:true})}
function wait(){ready()?build():setTimeout(wait,80)}wait();
})();