(function(){
const wait=()=>{if(!(window.DATA&&DATA.length&&window.ACT&&document.getElementById('actview')))return setTimeout(wait,100);init()};
function headerH(){return document.querySelector('.top')?.getBoundingClientRect().height||0}
function chapterLabel(r){const raw=String(r?.[1]||'').replace(/\s+/g,' ').trim();if(!raw)return 'Pozostałe';const m=raw.match(/((?:DZIAŁ|ROZDZIAŁ|ODDZIAŁ)\s+[IVXLCDM0-9]+(?:[A-Z])?)(?:\s*[.:-]?\s*)(.*)/i);return m?(m[1].toUpperCase()+(m[2]?' — '+m[2].trim():'')):raw}
function patchChapters(){document.querySelectorAll('.drawer-chapter').forEach(d=>{const first=d.querySelector('.drawer-article'),id=first?.dataset.id,r=ACT?.[3]?.find(x=>x[0]===id),s=d.querySelector('summary');if(s&&r)s.innerHTML='<span class="chapter-ico">▾</span>'+esc(chapterLabel(r))})}
function exactSearchJump(item,term){const id=item.dataset.target;if(!id)return;const el=document.getElementById(id);if(!el)return;const walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);const needle=term.toLocaleLowerCase('pl');let n,hit=null;while(n=walker.nextNode()){if((n.nodeValue||'').toLocaleLowerCase('pl').includes(needle)){hit=n;break}}if(!hit){el.scrollIntoView({block:'center'});el.classList.add('search-hit-block');setTimeout(()=>el.classList.remove('search-hit-block'),2500);return}const text=hit.nodeValue,idx=text.toLocaleLowerCase('pl').indexOf(needle),mark=document.createElement('mark');mark.className='search-hit';mark.textContent=text.slice(idx,idx+term.length);const after=hit.splitText(idx);after.nodeValue=after.nodeValue.slice(term.length);after.parentNode.insertBefore(mark,after);requestAnimationFrame(()=>{const y=scrollY+mark.getBoundingClientRect().top-headerH()-24;scrollTo({top:Math.max(0,y),behavior:'smooth'});mark.classList.add('show')});setTimeout(()=>{mark.classList.remove('show');setTimeout(()=>mark.replaceWith(document.createTextNode(mark.textContent)),700)},1900)}
function enhanceSearch(){const box=document.getElementById('results'),q=document.getElementById('q');if(!box||!q)return;box.addEventListener('click',e=>{const a=e.target.closest('.search-item');if(!a)return;const term=q.value.trim();if(term.length<2)return;const href=a.getAttribute('href')||'';const id=href.startsWith('#')?href.slice(1):null;if(id)a.dataset.target=id;setTimeout(()=>exactSearchJump(a,term),80)},true)}
function layoutToggle(){const d=document.querySelector('.drawer'),btn=d?.querySelector('.drawer-expand');if(!d||!btn)return;let mode=localStorage.getItem('police-law-layout')||'overlay';function apply(){document.body.dataset.navmode=mode;btn.textContent=mode==='split'?'⇱':'⇲';btn.title=mode==='split'?'Menu jako panel — przełącz na nakładkę':'Menu jako nakładka — przełącz na panel';if(mode==='split'&&innerWidth>=760){d.classList.add('open');document.body.classList.add('drawer-open');document.querySelector('.drawer-backdrop')?.classList.remove('open')}}btn.onclick=()=>{mode=mode==='split'?'overlay':'split';localStorage.setItem('police-law-layout',mode);apply()};apply();window.addEventListener('resize',apply)}
function articleStars(){const view=document.getElementById('actview');const install=()=>{view.querySelectorAll('.legal-unit').forEach(unit=>{if(unit.querySelector(':scope > .unit-head .unit-star'))return;const h=unit.querySelector(':scope > .unit-head');if(!h)return;const id=unit.id,b=document.createElement('button');b.className='unit-star';b.type='button';b.dataset.article=id;b.innerHTML='☆';b.title='Zapisz ten artykuł';b.onclick=()=>{if(typeof ACT==='undefined')return;let xs=[];try{xs=JSON.parse(localStorage.getItem('police-law-bookmarks-v1')||'[]')}catch(_){}const i=xs.findIndex(x=>x.id===id),r=ACT[3].find(x=>x[0]===id);if(i>=0)xs.splice(i,1);else if(r)xs.unshift({id,act:ACT[0],num:r[2],topic:r[3]||''});localStorage.setItem('police-law-bookmarks-v1',JSON.stringify(xs));refresh()};h.appendChild(b)});refresh()};function refresh(){let xs=[];try{xs=JSON.parse(localStorage.getItem('police-law-bookmarks-v1')||'[]')}catch(_){}const set=new Set(xs.map(x=>x.id));view.querySelectorAll('.unit-star').forEach(b=>{const on=set.has(b.dataset.article);b.classList.toggle('on',on);b.textContent=on?'★':'☆'})}new MutationObserver(()=>{install();setTimeout(patchChapters,30)}).observe(view,{childList:true,subtree:true});install();document.querySelector('.article-bookmark')?.remove()}
function init(){enhanceSearch();layoutToggle();articleStars();setTimeout(patchChapters,100);new MutationObserver(patchChapters).observe(document.querySelector('.drawer-article-list')||document.body,{childList:true,subtree:true})}wait();
})();