(function(){
const wait=()=>{if(!(Array.isArray(DATA)&&DATA.length&&ACT&&document.getElementById('actview')))return setTimeout(wait,100);init()};
const ACT_LANDING_ENABLED=false;
const CHAPTER_HINTS={uop:['Postanowienia ogólne','Zakres działania Policji','Organizacja Policji','Uprawnienia policjantów','Służba w Policji','Prawa i obowiązki','Świadczenia i mieszkania','Odpowiedzialność dyscyplinarna'],kw:['Zasady odpowiedzialności','Kary i środki','Wykroczenia'],kk:['Zasady odpowiedzialności karnej','Kary i środki karne','Przestępstwa'],kpk:['Przepisy ogólne','Uczestnicy postępowania','Dowody','Środki przymusu','Postępowanie przygotowawcze','Postępowanie sądowe'],kpow:['Zasady postępowania','Uczestnicy i czynności','Postępowanie przed sądem'],spb:['Zasady stosowania środków','Środki przymusu bezpośredniego','Broń palna'],prd:['Zasady ruchu drogowego','Pojazdy i kierujący','Kontrola ruchu drogowego'],cudz:['Zasady pobytu','Kontrola i powrót'],nieletni:['Zasady i środki','Postępowanie wobec nieletnich']};
const ACT_ICONS={uop:'🛡️',kw:'⚠️',kk:'⚖️',kpk:'🔎',kpow:'📋',spb:'✋',prd:'🚓',cudz:'🪪',nieletni:'👥',z768:'👮',z360:'🚐',z805:'⭐'};
function headerH(){return document.querySelector('.top')?.getBoundingClientRect().height||0}
function rawChapter(r){return String(r?.[1]||'').replace(/\s+/g,' ').trim()}
function chapterLabel(r,index){const raw=rawChapter(r);if(!raw)return 'Pozostałe';const m=raw.match(/((?:DZIAŁ|ROZDZIAŁ|ODDZIAŁ)\s+[IVXLCDM0-9]+(?:[A-Z])?)(?:\s*[.:-]?\s*)(.*)/i);if(!m)return raw;const prefix=m[1].replace(/\s+/g,' '),title=(m[2]||'').trim();if(title)return prefix+' — '+title;const hints=CHAPTER_HINTS[ACT?.[0]]||[];return prefix+' — '+(hints[index]||inferChapterTitle(r)||'Pozostałe przepisy')}
function inferChapterTitle(r){const t=String(r?.[3]||'').trim().replace(/[.;:]$/,'');if(!t)return'';return t.length>34?t.slice(0,32).replace(/\s+\S*$/,'')+'…':t}
function articleNumber(row,node){let x=String(row?.[2]||node?.dataset?.full||node?.textContent||'').trim();x=x.replace(/^Art\.\s*/i,'').replace(/^A\.\s*/i,'');return x}
function patchChapters(){let i=0;document.querySelectorAll('.drawer-chapter').forEach(d=>{const first=d.querySelector('.drawer-article'),id=first?.dataset.id,r=ACT?.[3]?.find(x=>x[0]===id),s=d.querySelector('summary'),chapterIndex=i++;if(s&&r&&!s.querySelector('.chapter-heading'))s.innerHTML='<span class="chapter-ico">▾</span>'+esc(chapterLabel(r,chapterIndex));d.querySelectorAll('.drawer-article').forEach(a=>{const n=a.querySelector('.da-num');if(!n)return;const row=ACT?.[3]?.find(x=>x[0]===a.dataset.id),num=articleNumber(row,n);if(num){n.dataset.full='Art. '+num;n.dataset.short='A. '+num;n.innerHTML='<span class="da-prefix">A.</span> '+esc(num)}})})}
function compactMarkers(on){document.querySelectorAll('#actview .marker').forEach(m=>{let full=m.dataset.fullMarker||m.textContent.trim();if(/^u\.\s/i.test(full))full=full.replace(/^u\.\s/i,'ust. ');if(/^p\.\s/i.test(full))full=full.replace(/^p\.\s/i,'pkt ');if(/^l\.\s/i.test(full))full=full.replace(/^l\.\s/i,'lit. ');m.dataset.fullMarker=full;const compact=full.replace(/^ust\.\s*/i,'u. ').replace(/^pkt\s*/i,'p. ').replace(/^lit\.\s*/i,'l. ');m.textContent=on?compact:full})}
function patchArticlePrefixes(){document.querySelectorAll('#actview .unit-title').forEach(t=>{if(t.querySelector('.art-prefix'))return;const nodes=[...t.childNodes],n=nodes.find(x=>x.nodeType===3&&/^\s*Art\.\s*/i.test(x.nodeValue||''));if(!n)return;const txt=n.nodeValue,m=txt.match(/^(\s*)(Art\.)(\s*)(.*)$/i);if(!m)return;const frag=document.createDocumentFragment();if(m[1])frag.append(m[1]);const s=document.createElement('span');s.className='art-prefix';s.textContent=m[2];frag.append(s,m[3]);if(m[4])frag.append(m[4]);n.replaceWith(frag)})}
function exactSearchJump(item,term){const id=item.dataset.target;if(!id)return;const el=document.getElementById(id);if(!el)return;const walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);const needle=term.toLocaleLowerCase('pl');let n,hit=null;while(n=walker.nextNode()){if((n.nodeValue||'').toLocaleLowerCase('pl').includes(needle)){hit=n;break}}if(!hit){el.scrollIntoView({block:'center'});el.classList.add('search-hit-block');setTimeout(()=>el.classList.remove('search-hit-block'),2500);return}const text=hit.nodeValue,idx=text.toLocaleLowerCase('pl').indexOf(needle),mark=document.createElement('mark');mark.className='search-hit';mark.textContent=text.slice(idx,idx+term.length);const after=hit.splitText(idx);after.nodeValue=after.nodeValue.slice(term.length);after.parentNode.insertBefore(mark,after);requestAnimationFrame(()=>{const y=scrollY+mark.getBoundingClientRect().top-headerH()-10;scrollTo({top:Math.max(0,y),behavior:'smooth'});mark.classList.add('show')});setTimeout(()=>{mark.classList.remove('show');setTimeout(()=>mark.replaceWith(document.createTextNode(mark.textContent)),700)},1900)}
function enhanceSearch(){const box=document.getElementById('results'),q=document.getElementById('q');if(!box||!q)return;box.addEventListener('click',e=>{const a=e.target.closest('.search-item');if(!a)return;const term=q.value.trim();if(term.length<2)return;const href=a.getAttribute('href')||'';const id=href.startsWith('#')?href.slice(1):null;if(id)a.dataset.target=id;document.body.classList.add('act-selected');setTimeout(()=>{patchArticlePrefixes();exactSearchJump(a,term)},100)},true)}
function simplifyDrawerTools(){const d=document.querySelector('.drawer');if(!d)return;const tools=d.querySelector('.drawer-tools'),expand=d.querySelector('.drawer-expand');if(!tools||!expand)return;[...tools.querySelectorAll('button')].forEach(b=>{if(b!==expand)b.style.display='none'});expand.innerHTML='<span aria-hidden="true">↘</span>';expand.title='Wróć do pełnego widoku';expand.setAttribute('aria-label','Wróć do pełnego widoku');expand.onclick=()=>{d.classList.remove('open');document.body.classList.remove('drawer-open','drawer-visible');d.setAttribute('aria-hidden','true')}}
function actLanding(){const main=document.getElementById('start');if(!main||document.getElementById('actLanding'))return;const landing=document.createElement('section');landing.id='actLanding';landing.className='act-landing';landing.innerHTML='<div class="landing-head"><h1>Wybierz akt prawny</h1><p>Szybki dostęp do bazy przepisów</p></div><div class="act-tiles"></div>';const box=landing.querySelector('.act-tiles');DATA.forEach(A=>{const m=META[A[0]]||[A[0],A[1],''],b=document.createElement('button');b.className='act-tile';b.innerHTML='<span class="tile-icon">'+(ACT_ICONS[A[0]]||'§')+'</span><span class="tile-copy"><b>'+esc(m[0])+'</b><small>'+esc(m[1])+'</small></span><span class="tile-arrow">›</span>';b.onclick=()=>{document.body.classList.add('act-selected');renderAct(A[0],null,false);setTimeout(()=>{patchArticlePrefixes();const id=ACT?.[3]?.[0]?.[0];if(id&&typeof jump==='function')jump(id,false);window.scrollTo({top:Math.max(0,(document.getElementById(id)?.offsetTop||0)-headerH()-8),behavior:'auto'})},80)};box.appendChild(b)});main.prepend(landing)}
function articleStars(){
  const view=document.getElementById('actview');
  function refresh(){let xs=[];try{xs=JSON.parse(localStorage.getItem('police-law-bookmarks-v1')||'[]')}catch(_){}const set=new Set(xs.map(x=>x.id));view.querySelectorAll('.unit-star').forEach(b=>{const on=set.has(b.dataset.article),next=on?'★':'☆';b.classList.toggle('on',on);if(b.textContent!==next)b.textContent=next})}
  const install=()=>{patchArticlePrefixes();view.querySelectorAll('.legal-unit').forEach(unit=>{if(unit.querySelector(':scope > .unit-head .unit-star'))return;const h=unit.querySelector(':scope > .unit-head');if(!h)return;const id=unit.id,b=document.createElement('button');b.className='unit-star';b.type='button';b.dataset.article=id;b.innerHTML='☆';b.title='Przytrzymaj, aby edytować ulubione';h.appendChild(b)});refresh();window.dispatchEvent(new CustomEvent('police-law-stars-ready'))};
  let queued=false;const observer=new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{observer.disconnect();try{patchChapters();patchArticlePrefixes();compactMarkers(document.body.classList.contains('drawer-open'));install()}finally{observer.observe(view,{childList:true,subtree:true});queued=false}})});observer.observe(view,{childList:true,subtree:true});install();document.querySelector('.article-bookmark')?.remove()
}
function forceFixedHeader(){const h=document.querySelector('.top');if(!h)return;const sync=()=>document.documentElement.style.setProperty('--topH',h.offsetHeight+'px');sync();new ResizeObserver(()=>requestAnimationFrame(sync)).observe(h)}
function watchDrawer(){const d=document.querySelector('.drawer');if(!d)return;new MutationObserver(()=>{const on=d.classList.contains('open');document.body.classList.toggle('drawer-visible',on);requestAnimationFrame(()=>{patchChapters();patchArticlePrefixes();compactMarkers(on)})}).observe(d,{attributes:true,attributeFilter:['class']})}
function init(){forceFixedHeader();enhanceSearch();simplifyDrawerTools();articleStars();if(ACT_LANDING_ENABLED)actLanding();else document.body.classList.add('act-selected');watchDrawer();setTimeout(()=>{patchChapters();patchArticlePrefixes();compactMarkers(document.body.classList.contains('drawer-open'))},120)}wait();
})();
